# added sonar properties to generate report
sonar.projectKey=base_tataplay_org_prm-nxt_prm-nxt-sales_AZIy6mBb1r-taeCknfNW
sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Specify the directories where the source code is located
sonar.sources=src


# Include only .js files (excluding .test.js files using exclusions)
sonar.inclusions=src/components/**/*.tsx,src/screens/**/*.tsx,src/app/**/*.tsx,src/navigation/**/*.tsx,src/services/**/*.ts,src/store/**/*.ts,src/wrappers/**/*.tsx
sonar.exclusions=src/**/*.stories.tsx,src/**/*.test.tsx,src/**/*.styles.tsx

# Include files and directories from test coverage (coverage exclusions)
sonar.coverage.inclusions=src/components/**/*.tsx,src/screens/**/*.tsx,src/app/**/*.tsx,src/navigation/**/*.tsx,src/services/**/*.ts,src/store/**/*.ts,src/wrappers/**/*.tsx
sonar.coverage.exclusions=src/**/*.test.tsx,src/**/*.stories.tsx,src/**/*.styles.tsx