import { Typography } from 'styles';
import i18next from 'i18next';
import { ROUTE, VALUE_TYPE } from './strings';

export const PROPERTIES = {
  PRIMARY_MODULES: [
    'Customer Recharge',
    'Recharge Reversal',
    'Confirm Recharge Reversal',
    'Last 20 Recharge Transactions',
    'TSK Refund',
    'Customer Service',
    'FAQ',
    'Change EVD Pin',
    'RMN Update',
  ],
  CUSTOMER_RECHARGE: {
    RECHARGE_FLEXI_PLAN: [
      { key: 'flexiRechargeAmountAnnual', subItems: [{ key: 'flexiAnnualBonus' }, { key: 'flexiDealerIncentiveAnnual' }] },
      { key: 'flexiRechargeAmountSemiAnnual', subItems: [{ key: 'flexiSemiAnnualBonus' }, { key: 'flexiDealerIncentiveSemiAnnual' }] },
    ],
    RECHARGE_WINBACK_FLEXI: [
      { key: 'annualWinbackOffer', subItems: [{ key: 'cashbackValueAnnual' }, { key: 'dealerMarginAnnual' }] },
      { key: 'semiAnnualWinbackOffer', subItems: [{ key: 'cashbackValueSemi' }, { key: 'dealerMarginSemi' }] },
      { key: 'quarterWinbackOffer', subItems: [{ key: 'cashbackValueQuarter' }, { key: 'dealerMarginQuarter' }] },
    ],
    RECHARGE_BINGE_PLAN: [{ key: 'bingeRechargeValue' }],
    OTHER_RECHARGE_OPTIONS: [
      { key: 'recommendedMonthlyRecharge', separator: ' -' },
      { key: 'semiAnnualRecharge', separator: ' -' },
      { key: 'annualRecharge', separator: ' -' },
      { key: 'lastRecharge', separator: ' -' },
    ],
    VALIDATE_SUBSCRIBER0: [{ key: 'subId', borderRight: true }, { key: 'customerName' }],
    VALIDATE_SUBSCRIBER1: [{ key: 'maskedRMN', borderRight: true }, { key: 'customerName' }],
    VALIDATE_SUBSCRIBER2: [{ key: 'monthlyRecharge', type: VALUE_TYPE.AMOUNT, borderRight: true }, { key: 'connectionType' }],
    VALIDATE_SUBSCRIBER3: [{ key: 'lastRechargeAmount', type: VALUE_TYPE.AMOUNT, borderRight: true }, { key: 'lastRechargeDate' }],
    CONFIRM_RECHARGE: [{ key: 'subscriberInfo' }, { key: 'amount', type: VALUE_TYPE.AMOUNT }, { key: 'subscriberBalance', type: VALUE_TYPE.AMOUNT }, { key: 'tskNumber' }],
    CONFIRM_RECOMENDED_RECHARGE: [{ key: 'subscriberInfo' }, { key: 'amount', type: VALUE_TYPE.AMOUNT }, { key: 'subscriberBalance', type: VALUE_TYPE.AMOUNT }],
    CONFIRM_OFFER_RECHARGE: [{ key: 'subscriberInfo' }, { key: 'amount', type: VALUE_TYPE.AMOUNT }, { key: 'subscriberBalance', type: VALUE_TYPE.AMOUNT }],
    DYNAMIC_OFFERS: [{ key: 'offerType' }, { key: 'packPrice', type: VALUE_TYPE.CURRENCY }, { key: 'offerDesc' }, { key: 'dealerIncentiveMsg', type: VALUE_TYPE.CURRENCY }],
    MAHA_BUMPER_OFFERS: [{ key: 'friendlyName' }, { key: 'stdPriUnit', type: VALUE_TYPE.AMOUNT }, { key: 'boxType' }, { key: 'uom' }, { key: 'margin' }, { key: 'customerBonus' }],
    WINBACK_OFFERS: [{ key: 'friendlyName' }, { key: 'stdPriUnit', type: VALUE_TYPE.AMOUNT }, { key: 'boxType' }, { key: 'uom' }, { key: 'margin' }, { key: 'customerBonus' }],
    RECHARGE_OPTIONS: [
      { text: 'With Recharge', value: 'withRecharge' },
      { text: 'Without Recharge', value: 'withoutRecharge' },
    ],
    OFFER_SEARCH_KEYS: ['name', 'nameNT', 'margin', 'friendlyName', 'friendlyNameNT'],
    DYNAMIC_OFFER_SEARCH_KEYS: ['offerType', 'offerTypeNT', 'packPrice', 'offerDesc', 'offerDescNT', 'dealerIncentiveMsg'],

    BALANCE: 'balance',
    BINGE_RECHARGE_VALUE: 'bingeRechargeValue',
    U: 'U',
    N: 'N',
    FLEXI_PLAN_INFO: [{ key: 'partnerMargin' }, { key: 'subscriberOffer' }],
    DURATION_DATA: [
      {
        name: 'All',
        value: 'All',
      },
      {
        name: 'Monthly',
        value: 'Monthly',
      },
      {
        name: 'Semi-Annual',
        value: 'Semi-Annual',
      },
      {
        name: 'Annual',
        value: 'Annual',
      },
    ],
    TABLE_DATA: [
      { range: 'flexirechargeAmount', value: 'dealermargin' },
      { range: '<=1999', value: 75 },
      { range: '2000 to 2999', value: 100 },
      { range: '3000 to 3999', value: 125 },
      { range: '>=4000', value: 150 },
    ],
  },
  RECHARGE_REVERSAL: {
    CONFIRM_REVERSAL: [
      { key: 'transactionID' },
      { key: 'subscriberID' },
      { key: 'amount', type: VALUE_TYPE.AMOUNT },
      { key: 'evdId' },
      { key: 'evdMobileNumber' },
      { key: 'dateOfRecharge' },
    ],
  },
  TRANSACTION_HISTORY: {
    GET_TRANSACTIONS: [{ key: 'subscriberId' }, { key: 'transactionId' }, { key: 'transactionDate' }, { key: 'amount' }, { key: 'bingeRechargeFlag' }],
  },

  RECHARGE_WINBACK: {
    CALL_SUBSCRIBER_DETAILS: [{ key: 'subscriberId' }, { key: 'mobileNumber' }, { key: 'subscriberName' }, { key: 'status' }, { key: 'curBalance' }, { key: 'validity' }],
    PACKS_DURATION_FILTER: [
      { value: 'All', text: 'All' },
      { value: 'Semi-Annual', text: 'Semi-Annual' },
      { value: 'Annual', text: 'Annual' },
    ],
    PACKAGE_OFFERS: [{ key: 'offerPrice' }, { key: 'yourMargin' }, { key: 'details' }],
  },

  EVD_BALANCE_INFO_KEY: {
    RECHARGE_TRANSACTION: [{ key: 'subscriberID' }, { key: 'transactionID' }, { key: 'txnDate' }, { key: 'amount' }, { key: 'bingeRechargeFlag' }],
    OTF_CREDIT_DETAILS: [{ key: 'subId' }, { key: 'transId' }, { key: 'otfDateTime' }, { key: 'bonusAmount' }, { key: 'msg5' }],
    BALANCE_TRANSFER_DETAILS: [
      { key: 'donorName' },
      { key: 'recipientName' },
      { key: 'donorMdn' },
      { key: 'recipientMdn' },
      { key: 'transactionID' },
      { key: 'amount' },
      { key: 'txnDate' },
    ],
    CONSOLIDATED_TRANSACTIONS: [{ key: 'txnId' }, { key: 'otfDate' }, { key: 'bingeFlag' }, { key: 'amount' }, { key: 'subId' }, { key: 'operation' }],
    TABLE_ROUTES: [
      'rechargeTransaction',
      'otfCreditDetails',
      'balanceTransferDetails',
      'consolidatedTransaction',
      'rechargeTransactionFos',
      'consolidatedTransactionFos',
      'balanceTransferDetailsFos',
      'otfCreditDetailsFos',
      'evdBalanceInfo',
    ],
  },

  ETSK_REGISTRATION: {
    TOTAL_COUNT: [{ key: 'NoOfConnection' }, { key: 'totalPacks' }, { key: 'totalChannels' }],
    BOX_FEE: [
      { key: 'addBoxPrice', type: VALUE_TYPE.AMOUNT },
      { key: 'tskValue', type: VALUE_TYPE.AMOUNT },
    ],
    NETWORK_CAPACITY: [{ key: 'productName', type: VALUE_TYPE.AMOUNT }],
    CUSTOMER_INFORMATION: [
      { key: 'name' },
      { key: 'primaryMobileNo' },
      { key: 'emailAddress' },
      { key: 'language' },
      { key: 'sec_lang' },
      { key: 'pincode' },
      { key: 'addressLine1' },
      { key: 'state' },
      { key: 'city' },
      { key: 'district' },
    ],
    BOOKING_FORM_NUMBER: [{ key: 'bookingFormNumber' }],
    CUSTOMER_DETAILS_ETSK: [{ key: 'subscriberId', borderRight: true }, { key: 'customerName', borderRight: true }, { key: 'bookingFormNumber' }],
    DHAMAKA_LIST: [
      { category: 'Dhamaka HD ETSK New offer 3600', rechargeAmount: '3600', rechargeEnabled: 'N', text: 'Dhamaka offer for {count} HD' },
      { category: 'Dhamaka HD ETSK New offer COD 3600', rechargeAmount: '3600', rechargeEnabled: 'Y', text: 'Dhamaka COD offer for {count} HD' },
      { category: 'Non ODU METSK Dhamaka', rechargeAmount: '3100', rechargeEnabled: 'N', text: 'Non ODU Dhamaka' },
      { category: 'Non ODU METSK Dhamaka COD Trade', rechargeAmount: '3100', rechargeEnabled: 'Y', text: 'Non ODU Dhamaka COD' },
      { category: 'Dhamaka New Android ETSK offer 3600', rechargeAmount: '3600', rechargeEnabled: 'N', text: 'Dhamaka offer for {count} Android' },
      { category: 'Dhamaka New Android ETSK offer COD 3600', rechargeAmount: '3600', rechargeEnabled: 'Y', text: 'Dhamaka COD offer for {count} Android' },
      { category: 'Dhamaka New Android ETSK offer 6000', rechargeAmount: '6000', rechargeEnabled: 'N', text: 'Dhamaka offer for {count} Android' },
      { category: 'Dhamaka New Android ETSK offer COD 6000', rechargeAmount: '6000', rechargeEnabled: 'Y', text: 'Dhamaka COD offer for {count} Android' },
      { category: 'Non ODU METSK Dhamaka COD', rechargeAmount: '3100', rechargeEnabled: 'Y', text: 'Non ODU Dhamaka COD' },
      { category: 'Non ODU METSK Dhamaka COD Others', rechargeAmount: '3100', rechargeEnabled: 'Y', text: 'Non ODU Dhamaka COD' },
    ],
    DHAMAKA_COD_NAMES: [
      'Non ODU Dhamaka COD',
      'Dhamaka COD offer for 1 HD',
      'Dhamaka COD offer for 2 HD',
      'Dhamaka COD offer for 3 HD',
      'Dhamaka COD offer for 4 HD',
      'Dhamaka COD offer for 1 Android',
      'Dhamaka COD offer for 2 Android',
      'Dhamaka COD offer for 3 Android',
      'Dhamaka COD offer for 4 Android',
    ],
  },
  DEALER_NUMBER: {
    DEALER_RMN: [{ key: 'RetailerRMN' }],
  },

  MODIFY_PACK: {
    CUSTOMER_DETAILS: [{ key: 'subscriberNameMp' }, { key: 'subscriberIdMp' }, { key: 'mobileNum' }],
  },

  ACTIVATION_STATUS: {
    CUSTOMER_RMN: [{ key: 'customerRmn' }],
    BCP_ACTIVATION_STATUS: [{ key: 'subscriberId' }, { key: 'workOrderNo' }],
    WO_INFORMATION: ['workOrderDetails', 'upgradeWODetails', 'otherDetails'],
    RELATED_LINKS: ['packagesInformation', 'WOAndOtherDetails', 'rechargeTransactions'],
    WO_DETAILS: [
      { key: 'woNumber' },
      { key: 'woStatus' },
      { key: 'woCreatedDateAndTime' },
      { key: 'plannedDateAndTime' },
      { key: 'completedDateAndTime' },
      { key: 'cancelledDateAndTime' },
      { key: 'reasonCode' },
      { key: 'resolutionCode' },
    ],
    WO_ISP_ASI_DETAILS: [{ key: 'ispNameKey' }, { key: 'ispMobileKey' }, { key: 'asiName' }, { key: 'asiMobile' }] as const,
    WO_OTHER_DETAILS: [{ key: 'tskNumber' }, { key: 'bookingFormNumber' }, { key: 'boxType' }, { key: 'connectionType' }, { key: 'alternateMobNumber' }],
    CONFIG: {
      evd: 'MOBWEB',
      eai: 'MOBDATA',
      sms: '',
      hma: 'HMA',
      dsktp: 'MOBDESKTOP',
      source: 'PRMNXTSALES',
    },
  },

  EVD_BALANCE_INFO: {
    myEvdBalance: 'My EVD balance',
    fosDealerBalance: 'FOS/Dealer balance',
  },
  BOX_UPGRADE: {
    BOX_UPGRADE_TO: [{ key: 'boxTypeChangeTo' }],
    CUSTOMER_INFORMATION: [{ key: 'name' }, { key: 'primaryMobileNo' }, { key: 'state' }, { key: 'status' }],
  },
  RAISE_REQUEST: {
    preferredMaxDate: 29,
    accountUpdate: 'Account update',
    requestForServices: 'Request for services',
    unableToViewServices: 'Unable to view services',
    natureOfRequest: 'natureOfRequest',
    deactivated: 'Deactivated',
    fieldRepair: 'Field Repair',
    ocsFlag: 'Y',
    requestOcsDateTime: 'requestOcsDateTime',
    requestDateTime: 'requestDateTime',
    typeOfRequest: 'typeOfRequest',
    resumption: 'Resumption',
    suspension: 'Suspension',
    selectDate: 'selectDate',
    selectTime: 'selectTime',
    preferredDate: 'preferredDate',
    suspensionReason: 'suspensionReason',
    suspensionDate: 'suspensionDate',
    resumptionDate: 'resumptionDate',
    subscriberInfo: 'subscriberInfo',
    subId: 'subId',
    name: 'name',
    category: 'category',
    description: 'description',
    raiseTheRequest: 'raiseTheRequest',
    trackTheRequest: 'trackTheRequest',
    formValidation: {
      subscriberInfo: {
        field_name: 'subscriberInfo',
        validation: [
          {
            field_id: 'subscriberInfo',
            type: 'required',
            message: 'subscriberInfoRequired',
            value: null,
          },
          {
            field_id: 'subscriberInfo',
            type: 'fixLength',
            message: 'subscriberInfoFixLength',
            value: '10',
          },
          {
            field_id: 'subscriberInfo',
            type: 'numeric',
            message: 'subscriberInfoNumeric',
            value: null,
          },
        ],
      },
      natureOfRequest: {
        field_name: 'natureOfRequest',
        validation: [
          {
            field_id: 'natureOfRequest',
            type: 'required',
            message: 'natureOfRequestRequired',
            value: null,
          },
        ],
      },
      typeOfRequest: {
        field_name: 'typeOfRequest',
        validation: [
          {
            field_id: 'typeOfRequest',
            type: 'required',
            message: 'typeOfRequestRequired',
            value: null,
          },
        ],
      },
      suspensionReason: {
        field_name: 'suspensionReason',
        validation: [
          {
            field_id: 'suspensionReason',
            type: 'required',
            message: 'suspensionReasonRequired',
            value: null,
          },
        ],
      },
      suspensionDate: {
        field_name: 'suspensionDate',
        validation: [
          {
            field_id: 'suspensionDate',
            type: 'required',
            message: 'suspensionDateRequired',
            value: null,
          },
        ],
      },
      resumptionDate: {
        field_name: 'resumptionDate',
        validation: [
          {
            field_id: 'resumptionDate',
            type: 'required',
            message: 'resumptionDateRequired',
            value: null,
          },
        ],
      },
      selectDate: {
        field_name: 'selectDate',
        validation: [
          {
            field_id: 'selectDate',
            type: 'required',
            message: 'selectDateRequired',
            value: null,
          },
        ],
      },
      preferredDate: {
        field_name: 'preferredDate',
        validation: [
          {
            field_id: 'preferredDate',
            type: 'required',
            message: 'selectDateRequired',
            value: null,
          },
        ],
      },
      selectTime: {
        field_name: 'selectTime',
        validation: [
          {
            field_id: 'selectTime',
            type: 'required',
            message: 'selectTimeRequired',
            value: null,
          },
        ],
      },
      description: {
        field_name: 'description',
        validation: [
          {
            field_id: 'description',
            type: 'required',
            message: 'descriptionRequired',
            value: null,
          },
          {
            field_id: 'description',
            type: 'maxLength',
            message: 'descriptionMaxLength',
            value: '700',
          },
        ],
      },
    },
  },

  TRACK_REQUEST: {
    tableColumns: [
      {
        id: 1,
        accessorKey: 'requestNumber',
        label: 'request',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 2,
        accessorKey: 'subscriberId',
        label: 'subscriberId',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 3,
        accessorKey: 'natureOfRequest',
        label: 'natureRequest',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 4,
        accessorKey: 'requestType',
        label: 'woType',
        size: 200,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 5,
        accessorKey: 'description',
        label: 'description',
        size: 200,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 6,
        accessorKey: 'status',
        label: 'status',
        size: 150,
        ...Typography.fontName.medium,
        isRowFormatter: true,
        type: 'status',
      },
      {
        id: 7,
        accessorKey: 'source',
        label: 'source',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 8,
        accessorKey: 'openedDate',
        label: 'createdDate',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 9,
        accessorKey: 'closeDate',
        label: 'closeDate',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 10,
        accessorKey: 'resolutionCode',
        label: 'resolutionCode',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
    ],
  },

  TRACK_REQUEST_SR: {
    tableColumns: [
      {
        id: 1,
        accessorKey: 'requestNumber',
        label: 'request',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 2,
        accessorKey: 'natureOfRequest',
        label: 'natureRequest',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 3,
        accessorKey: 'requestType',
        label: 'type',
        size: 200,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 4,
        accessorKey: 'area',
        label: 'area',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 5,
        accessorKey: 'subArea',
        label: 'subArea',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 6,
        accessorKey: 'description',
        label: 'description',
        size: 200,
        isRowFormatter: true,
        type: 'centeredText',
      },
      {
        id: 7,
        accessorKey: 'status',
        label: 'status',
        size: 150,
        ...Typography.fontName.medium,
        isRowFormatter: true,
        type: 'status',
      },
      {
        id: 8,
        accessorKey: 'openedDate',
        label: 'createdDate',
        size: 150,
        isRowFormatter: true,
        type: 'centeredText',
      },
    ],
  },

  DETAILS_HEADER: {
    GET_HEADER_DETAILS: [{ key: 'mobileNoInHeader' }, { key: 'name' }],
  },

  EVD_TRANSFER: {
    selectedRadio: 'selectedRadio',
    forwardTransfer: 'forwardTransfer',
    reverseTransfer: 'reverseTransfer',
    asmTransfer: 'evdTransferAsm',
    selectedPartnerId: 'selectedPartnerId',
    amount: 'amount',
    showPassword: 'showPassword',
    pin: 'pin',
    fullAmount: 'Full Amount',
    customAmount: 'Custom Amount',
    forwardTransferSuccess: 'forwardTransferSuccess',
    reverseTransferSuccess: 'reverseTransferSuccess',
    transactionID: 'transactionID',
  },
  ROLES: {
    fos: 'FOS',
    dealer: 'Dealer',
    asi: 'ASI',
    asm: 'ASM',
    csm: 'CSM',
    employee: 'Employee',
    distributer: 'Distributor',
    ad: 'AD',
  },

  AUTO_EVD: {
    evdDetails: [{ key: 'userId' }, { key: 'name' }, { key: 'mdn' }, { key: 'outletType' }, { key: 'balance' }, { key: 'avgDailyRecharge' }, { key: 'thresholdSet' }],
    autoEvdSuccess: 'autoEvdSuccess',
    evdDetailsSearchKeys: ['dealerName', 'mdn', 'evdCode'],
    autoEvdHeader: ['userId', 'name', 'mdn', 'outletType', 'balance', 'avgDailyRecharge', 'thresholdSet', 'action'],
    tableHeaderAction: 'actions',
  },

  DASHBOARD: {
    cumulative: 'cumulative',
    monthWise: 'monthWise',
    monthWiseTableColumns: [
      {
        id: 1,
        accessorKey: 'parameter',
        label: 'Parameter',
        size: 160,
      },
      {
        id: 2,
        accessorKey: 'apr',
        label: 'Apr',
        size: 80,
      },
      {
        id: 3,
        accessorKey: 'may',
        label: 'May',
        size: 80,
      },
      {
        id: 4,
        accessorKey: 'jun',
        label: 'Jun',
        size: 80,
      },
      {
        id: 4,
        accessorKey: 'jul',
        label: 'Jul',
        size: 80,
      },
    ],
  },

  RESET_EVD: {
    otpTimer: 30,
    RESET_SUCCESS: [{ key: 'username' }],
    SUCCESS: 'SUCCESS',
    SELF: 'self',
    PARTNER: 'partner',
    oldPinLabel: 'oldPinLabel',
  },

  DEMO_BOX_DETAILS: {
    accountStatusFilter: 'accountStatusFilter',
    boxTypeFilter: 'boxTypeFilter',
    search: 'search',
  },
  CUSTOMER_OFFERS: {
    CUSTOMER_DETAILS: [{ key: 'subscriberId', borderRight: true }, { key: 'customerName' }],
    CUSTOMER_DETAILS_ETSK: [{ key: 'subscriberId', borderRight: true }, { key: 'customerName', borderRight: true }, { key: 'bookingFormNumber' }],
    SEARCH_KEYS: ['offerPrice', 'margin', 'details'],
    BINGLE_FLEXI_LITE: 'Binge flexi lite',
    WINBACK_OFFERS: [{ key: 'stdPriUnit', type: VALUE_TYPE.AMOUNT }, { key: 'boxType' }, { key: 'uom' }, { key: 'margin' }, { key: 'bonusDetails' }],
    RECHAARGE_WINBACK_OFFERS: [{ key: 'stdPriUnit', type: VALUE_TYPE.AMOUNT }, { key: 'margin' }, { key: 'detailsType' }, { key: 'bonus' }],
    DYNAMIC_OFFERS: [{ key: 'packPrice', type: VALUE_TYPE.AMOUNT }, { key: 'dealerIncentiveMsg' }, { key: 'offerDesc' }],
    MAHA_BUMPER_OFFERS: [{ key: 'stdPriUnit', type: VALUE_TYPE.AMOUNT }, { key: 'margin' }, { key: 'friendlyName' }],
    MY_OFFERS: [{ key: 'packPrice', type: VALUE_TYPE.AMOUNT }, { key: 'dealerIncentiveMsg' }, { key: 'offerDesc' }],
    PACKAGE_OFFERS: [{ key: 'offerPrice' }, { key: 'yourMargin' }, { key: 'details' }],
    MAHA_BUMPER: 'Mahabumper Offers',
    WINBACK_OFFERS_KEY: 'Bumper Offers',
    MY_OFFERS_KEY: 'My Offers',
    ADDITIONAL_SEARCH_KEYS: ['offerType', 'name', 'offerTypeNT', 'offerDescNT', 'dealerIncentiveMsgNT', 'nameNT'],
    ETSK_REGISTRATION: [{ key: 'offerPrice', type: VALUE_TYPE.AMOUNT }],
  },
  BINGE_VIEW_DETAILS: {
    ICON_ARR: [
      { icon: 'cart', text: 'buyBingeFlexiLite' },
      { icon: 'choice', text: 'selectApps' },
      { icon: 'favoriteShow', text: 'enjoyFavoriteShows' },
    ],
  },
  EVD_MDN_CHANGE_DETAILS: {
    evdMdnChange: [{ key: 'partnerId' }, { key: 'partnerName' }, { key: 'oldRmn' }, { key: 'newRmn' }, { key: 'requestDate' }],
    dateRangeTitle: 'customDateRange',
    select: 'select',
    clear: 'clear',
    evdMdnChangeHeader: ['partnerId', 'partnerName', 'oldRmn', 'newRmn', 'requestDate', 'actions'],
    tableHeaderAction: 'actions',
  },
  CUSTOMER_INFORMATION: {
    DHAMAKA_LOCK_IN: 'dhamakaLockIn',
  },
  TSRA_LIFECYCLE: {
    subscriberDetails: [{ key: 'tsraName' }, { key: 'tsraMdn' }, { key: 'createdDate' }],
  },

  CUSTOMER_INVOICE: {
    invoiceTransaction: [{ key: 'subscriberId' }, { key: 'transactionId' }, { key: 'transactionDate' }, { key: 'amount', type: VALUE_TYPE.AMOUNT }, { key: 'bingeRechargeFlag' }],
    tableHeaderAction: 'actions',
    invoiceHeader: ['subscriberId', 'transactionId', 'transactionDate', 'amount', 'bingeRechargeFlag', 'action'],
  },
  DEALER_FEEDBACK: {
    feedbackID: 'feedbackID',
    pleaseSelectMonth: 'pleaseSelectMonth',
    pleaseValidateSubscriberId: 'pleaseValidateSubscriberId',
    success: 'SUCCESS',
    all: 'All',
    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    CMSSchemeAmountNotReceived: 'Scheme (CMS) amount not received',
    installationPaymentNotReceived: 'Only If TSRA - Installation payment not received',
    installationNotHappeningOnTime: 'Installation not happening on time',
  },

  MANAGE_HIERARCHY: {
    DIST_FILTER: [
      {
        id: 1,
        name: 'All',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 2,
        name: 'AD',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 3,
        name: 'FOS',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 4,
        name: 'Dealer',
        object: {},
        __typename: 'DropdownOption',
      },
    ],
    AD_FILTER: [
      {
        id: 1,
        name: 'All',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 3,
        name: 'FOS',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 4,
        name: 'Dealer',
        object: {},
        __typename: 'DropdownOption',
      },
    ],
    CREATE_PARTNER_ROLES: [
      { value: 'dealer', text: 'Dealer' },
      { value: 'fos', text: 'FOS' },
      { value: 'ad', text: 'AD' },
    ],
    CREATE_PARTNER_FOR_ASM: [{ value: 'dealer', text: 'Dealer' }],
    DISTRIBUTER_DETAILS: [{ key: 'name' }, { key: 'distributorMdn' }, { key: 'circleDesc' }],
    DISTRIBUTER_FOS_DETAILS: [{ key: 'name' }, { key: 'distributorMdn' }, { key: 'circleDesc' }, { key: 'fosName' }, { key: 'fosMobile' }],

    TYPES_OF_REPORT_FOR_ALL: [
      { value: 'Recharge', text: 'recharge' },
      { value: 'BT', text: 'balanceTransfer' },
      { value: 'Consolidated', text: 'consolidatedReport' },
      { value: 'Activation', text: 'activationScheme' },
    ],

    TYPES_OF_REPORT_FOR_DEALER: [
      { value: 'Recharge', text: 'recharge' },
      { value: 'Consolidated', text: 'consolidatedReport' },
    ],
  },

  HIDE_BACK_BUTTON_FOR_ROUTE: [
    ROUTE.WEB.SECONDARY_TSK_REGISTRATION,
    ROUTE.WEB.REGISTRATION_DETAILS,
    ROUTE.WEB.PRIMARY_REGISTRATION_CHANNELS,
    ROUTE.WEB.PRIMARY_TV_REG_SUCCESS,
    ROUTE.WEB.ETSK_REG_SUCCESS,
    ROUTE.WEB.ETSK_REGISTRATION_CHANNELS,
    ROUTE.WEB.DEALER_FEEDBACK_SUCCESS,
    ROUTE.WEB.CUSTOMER_OFFER_SUCCESS,
    ROUTE.WEB.WINBACK_SUCCESS,
    ROUTE.WEB.MANAGE_HIERARCHY_SUCCESS,
    ROUTE.WEB.CREATE_NEW_DEALER_SUCCESS,
    ROUTE.WEB.WO_RECREATION_CHANNELS,
    ROUTE.WEB.RE_PUSH_ORDER_CHANNELS,
    ROUTE.WEB.RE_PUSH_ORDER_SUCCESS,
    ROUTE.WEB.WORK_ORDER_RECREATION_SUCCEESS,
    ROUTE.WEB.ETSK_MULTI_TV_SUCCESS,
    ROUTE.WEB.ETSK_MULTI_TV_REPUSH_SUCCESS,
    ROUTE.WEB.ETSK_REPUSH_SUCCESS,
    ROUTE.WEB.MULTI_TV_SUMMAARY,
    ROUTE.WEB.MULTI_TV_SUCCESS,
    ROUTE.WEB.MULTI_TV_REGISTRATION,
    ROUTE.WEB.MULTI_TV_REGISTRATION_SUMMARY,
    ROUTE.WEB.DEMO_ACCOUNT_SUCCESS,
    ROUTE.WEB.BOX_UPGRADE_SUCCESS,
    ROUTE.WEB.QUOTATION_ETSK_CHANNELS,
    ROUTE.WEB.QUOTATION_PRIMARY_CHANNELS,
    ROUTE.WEB.QUOTATION_ETSK_SUCCESS,
    ROUTE.WEB.QUOTATION_PRIMARY_SUCCESS,
    ROUTE.WEB.QUOTATION_MULTITV_SUMMARY,
    ROUTE.WEB.QUOTATION_MULTITV_SELECTION,
    ROUTE.WEB.QUOTATION_MULTITV_SUCCESS,
    ROUTE.WEB.TSRA_APPROVAL_SUCCESS,
    ROUTE.WEB.PARTNER_APPROVAL_SUCCESS,
    ROUTE.WEB.PURCHASE_ORDER_DURATION,
    ROUTE.WEB.REGISTER_NEW_PAYMENT_ID,
    ROUTE.WEB.REGISTER_PAYMENT_OPTION,
    ROUTE.WEB.PURCHASE_ORDER_TRACK_DETAILS,
    ROUTE.WEB.PURCHASE_ORDER_DEALER_TRACK_DETAILS,
    ROUTE.WEB.PURCHASE_ORDER_FOS_TRACK_DETAILS,
    ROUTE.WEB.PURCHASE_ORDER_DEALER_DURATION,
    ROUTE.WEB.PURCHASE_ORDER_FOS_DURAION,
    ROUTE.WEB.PURCHASE_ORDER_TRACK_DETAILS_DEALER_POSM,
    ROUTE.WEB.PURCHASE_ORDER_TRACK_DETAILS_FOS_POSM,
    ROUTE.WEB.PURCHASE_ORDER_TRACK_DETAILS_ASM_POSM,
    ROUTE.WEB.EVD_RAISE_REQUEST,
    ROUTE.WEB.MATERIAL_RAISE_REQUEST,
    ROUTE.WEB.EVD_RAISE_REQUEST_SUCCESS,
    ROUTE.WEB.PURCHASE_ORDER_ASM_DURAION,
    ROUTE.WEB.DEALER_SUCCESS,
  ],

  DROPDOWN_QUERY_NAME: [
    'thresHoldFilter',
    'priceFilter',
    'daysFilter',
    'statusFilter',
    'winBackStatusDrop',
    'campaingnStatusDrop',
    'winBackSubCategoryNewDrop',
    'winBackSubCategoryDrop',
  ],
  PARTNER_QUERY: ['searchPartner', 'fetchChildPartnerDetails', 'languageList', 'locationDropdown'],
  LANG_LIST_SOUTH: ['ml', 'kn', 'ta'],
  PARTNER_APPROVAL: {
    APPROVAL_CARD_DETAILS: [{ key: 'partnerName' }, { key: 'role' }, { key: 'createdDate' }, { key: 'mobileNumber' }],
    PARTNER_ALL_DETAILS: [{ key: 'partnerName' }, { key: 'mobileNumber' }, { key: 'role' }, { key: 'id' }, { key: 'createdDate' }, { key: 'outlet' }, { key: 'pinCode' }],
    DISTRIBUTOR_DETAILS: [{ key: 'distributorName' }, { key: 'distributorMobileNumber' }, { key: 'distributorRole' }, { key: 'distributorId' }],
    tableHeaderAction: 'actions',
    partnerApprovalHeader: ['partnerName', 'role/outletType', 'createdDate', 'mobileNumber', 'moreDetails', 'actions'],
  },
  DEALER_STOCK: {
    stocksList: [{ key: 'purchaseCode' }, { key: 'stockInHand' }, { key: 'stockNorm' }, { key: 'xTslSugestedQty' }, { key: 'serializedFlg' }],
    tableColumns: [
      {
        id: 1,
        accessorKey: 'product',
        label: 'product',
        size: 140,
        isRowFormatter: true,
        type: 'leftAlignedText',
        alignment: 'left',
        headerAlignment: 'left',
      },
      {
        id: 2,
        accessorKey: 'purchaseCode',
        label: 'purchaseCode',
        size: 100,
        isRowFormatter: true,
        type: 'leftAlignedText',
        alignment: 'left',
        headerAlignment: 'left',
      },
      {
        id: 3,
        accessorKey: 'stockInHand',
        label: 'stockInHand',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
        alignment: 'center',
      },
      {
        id: 4,
        accessorKey: 'xTslSugestedQty',
        label: 'xTslSugestedQty',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
        alignment: 'center',
      },
      {
        id: 5,
        accessorKey: 'stockNorm',
        label: 'stockNorm',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
        alignment: 'center',
      },
      {
        id: 6,
        accessorKey: 'serializedFlg',
        label: 'serializedFlg',
        size: 100,
        isRowFormatter: true,
        type: 'centeredText',
        alignment: 'center',
      },
    ],
    PRODUCT_TYPE: {
      productTypes: [
        {
          id: 0,
          name: 'All',
          nameNT: 'All',
          value: 'All',
          object: {
            name: 'All',
            value: 'All',
            __typename: 'ProductObject',
          },
          __typename: 'ProductType',
        },
        {
          id: 1,
          name: 'EVD',
          nameNT: 'EVD',
          value: 'EVD',
          object: {
            name: 'EVD',
            value: 'EVD',
            __typename: 'ProductObject',
          },
          __typename: 'ProductType',
        },
        {
          id: 2,
          name: 'TSK',
          nameNT: 'TSK',
          value: 'VC',
          object: {
            name: 'TSK',
            value: 'VC',
            __typename: 'ProductObject',
          },
          __typename: 'ProductType',
        },
        {
          id: 3,
          name: 'RCV',
          nameNT: 'RCV',
          value: 'RCV',
          object: {
            name: 'RCV',
            value: 'RCV',
            __typename: 'ProductObject',
          },
          __typename: 'ProductType',
        },
        {
          id: 4,
          name: 'POS Material',
          nameNT: 'POS Material',
          value: 'POS Material',
          object: {
            name: 'POS Material',
            value: 'POS Material',
            __typename: 'ProductObject',
          },
          __typename: 'ProductType',
        },
      ],
      __typename: 'ProductTypesOutput',
    },
  },
  WO_RECREATION: {
    WO_STATUS: [
      'Scheduled',
      'In Progress',
      'Acknowledged',
      'Cancellations',
      'Closed',
      'Completed',
      'Consumed',
      'Declined',
      'ExcptnApproval',
      'Hard Closed',
      'Insuff Stock',
      'Invalid',
      'Modify',
      'On Hold',
      'Rescheduled',
      'Unscheduled',
      'Verified',
    ],
  },
  NOTIFICATION: {
    OPTION_DATA: [
      {
        id: 'ALL',
        name: 'ALL',
      },
      {
        id: 'FS',
        name: 'FS',
      },
      {
        id: 'INVENTORY',
        name: 'INVENTORY',
      },
      {
        id: 'WO',
        name: 'WO',
      },
    ],
  },
  SELECT_DATE: {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  } as Intl.DateTimeFormatOptions,
  CUSTOM_CALENDAR: {
    month: 'long',
    year: 'numeric',
  } as Intl.DateTimeFormatOptions,
  TOTAL_MONTHS: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  BINGE_DURATION: [
    { text: 'All', value: 'NA' },
    { text: 'MONTHLY', value: 'Monthly' },
    { text: 'Semi-Annual', value: 'Semi-Annual' },
    { text: 'Annual', value: 'Annual' },
  ],
  DEMO_ACCOUNT_CREATION: {
    DISTRIBUTER_DETAILS: [
      { key: 'name' },
      { key: 'mobileNo' },
      { key: 'partnerCode' },
      { key: 'partnerCircle' },
      { key: 'email' },
      { key: 'addressLine1' },
      { key: 'city' },
      { key: 'town' },
      { key: 'state' },
      { key: 'pincode' },
    ],
    CUSTOMER_DETAILS: [{ key: 'subscriberId', borderRight: false }],
    TYPE_OF_DEMO: [
      { text: 'Physical TSK', value: 'PhysicalTsk' },
      { text: 'METSK', value: 'ETSK' },
    ],
  },

  CANCEL_TSK_DETAILS: {
    TSK_DETAILS: [{ key: 'tskType' }, { key: 'tskSerialNumber' }, { key: 'price' }],
  },
  BOX_TYPE_CHANGE: {
    WO_STATUS: [
      'Scheduled',
      'In Progress',
      'Acknowledged',
      'Cancellations',
      'Closed',
      'Completed',
      'Consumed',
      'Declined',
      'Dispatched',
      'ExcptnApproval',
      'Hard Closed',
      'Insuff Stock',
      'Invalid',
      'Modify',
      'On Hold',
      'Rescheduled',
      'Verified',
    ],
    ELEGIBLE_BOXTYPE: ['SD', 'HD', 'Android'],
  },
  CUSTOMER_SERVICE: {
    REQUEST_TYPE: [
      {
        id: 'wo',
        name: 'Work Order',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'sr',
        name: 'Service Request',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'suspension',
        name: 'Suspension',
        object: {},
        __typename: 'DropdownOption',
      },
    ],
  },
  EXCLUSIVE_STORE: {
    WALK_IN: [
      { text: 'New Connection', value: 'New Connection' },
      { text: 'Recharge', value: 'Recharge' },
      { text: 'Service Complaint', value: 'Service Complaint' },
      { text: 'Enquiry of New Connection', value: 'Enquiry of New Connection' },
      { text: 'Enquiry of Pack', value: 'Enquiry of Pack' },
      { text: 'Sales of VAS(Value Added Service)', value: 'Sales of VAS' },
      { text: 'Box Upgrade', value: 'Box Upgrade' },
      { text: 'General Enquiry', value: 'General Enquiry' },
    ],
    CONNECTION_TYPE: [
      { text: 'Primary Registration', value: 'Primary' },
      { text: 'MultiTV Registration', value: 'Multi' },
    ],
    MONTH: {
      Jan: '01',
      Feb: '02',
      Mar: '03',
      Apr: '04',
      May: '05',
      Jun: '06',
      Jul: '07',
      Aug: '08',
      Sep: '09',
      Oct: '10',
      Nov: '11',
      Dec: '12',
    },
  },
  TSK_VOUCHER: {
    DISTRIBUTOR_DETAILS: [
      { key: 'distributorCode', label: 'distributorCode' },
      { key: 'distributorName', label: 'distributorNameTsk' },
      { key: 'dealerCode', label: 'dealerCode' },
      { key: 'dealerName', label: 'dealerName' },
      { key: 'dealerMobNo', label: 'dealerMobNo' },
    ],
    SUBSCRIBER_DETAILS: [
      { key: 'subscriberName', label: 'subscriberNameTsk' },
      { key: 'subscriberId', label: 'subscriberId' },
      // { key: 'subscriberMobile', label: 'subscriberMobile' },
    ],
    VOUCHER_DETAILS: [
      { key: 'voucherSerialNo', label: 'voucherSerialNo' },
      { key: 'voucherStatus', label: 'voucherStatus' },
      { key: 'voucherExpiryDate', label: 'voucherExpiryDate' },
      { key: 'inventoryLocation', label: 'inventoryLocation' },
    ],
    DATA: [
      { id: 'tskVoucherNumber', name: 'TSK Serial Number' },
      { id: 'manufactureSerialNo', name: 'Manufactured SL No.' },
      { id: 'digicardNo', name: 'Digicard No.' },
      { id: 'digicomp', name: 'Digicomp No.' },
    ],
  },
  TSRA_APPROVAL: {
    APPROVAL_CARD_DETAILS: [{ key: 'tsraNameNT' }, { key: 'tsraMobileNumber' }, { key: 'createdDateNT' }],
    tableHeaderAction: 'actions',
    partnerApprovalHeader: ['tsraCode', 'tsraNameNT', 'tsraMobileNumber', 'createdDate', 'actions'],
    APPROVE_OR_REJECT: [
      { value: 'approve', text: 'approve' },
      { value: 'reject', text: 'reject' },
    ],
  },
  LARGE_ICON: ['icons/partnerQuote.png'],
  FAQ: {
    HELP_LINE_NUMBERS: [
      { title: 'customerCare', num1: '1800 208 6633', num2: '1860 120 6633' },
      { title: 'dealerHelpline', num1: '080 6858 6858', num2: '080 6859 6859' },
      { title: 'dealerWhatsapp', num1: '8067028555', num2: '' },
    ],
  },
  PURCHASE_ORDER: {
    getPaymentTypes: () => [
      {
        id: 'All',
        name: i18next.t('strings.All'),
        nameNT: 'All',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'Pending',
        name: i18next.t('strings.pending'),
        nameNT: 'Pending',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'Approved',
        name: i18next.t('strings.approved'),
        nameNT: 'Approved',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'Rejected',
        name: i18next.t('strings.rejected'),
        nameNT: 'Rejected',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'Failed',
        name: i18next.t('strings.failed'),
        nameNT: 'Failed',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'SUBMITTED',
        name: i18next.t('strings.razorpayPending'),
        nameNT: 'Razorpay - Pending',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'COMPLETED',
        name: i18next.t('strings.razorpayCompleted'),
        nameNT: 'Razorpay - Completed',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'FAILED',
        name: i18next.t('strings.razorpayFailed'),
        nameNT: 'Razorpay - Failed',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: 'REFUNDED',
        name: i18next.t('strings.razorpayRefunded'),
        nameNT: 'Razorpay - Refunded',
        object: {},
        __typename: 'DropdownOption',
      },
    ],
    getDurationTypes: () => [
      {
        id: '3',
        name: i18next.t('strings.last3Days'),
        nameNT: 'Last 3 Days',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: '7',
        name: i18next.t('strings.lastoneWeek'),
        nameNT: 'Last One Week',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: '15',
        name: i18next.t('strings.last15Days'),
        nameNT: 'Last 15 Days',
        object: {},
        __typename: 'DropdownOption',
      },
      {
        id: '31',
        name: i18next.t('strings.last1Month'),
        nameNT: 'Last One Month',
        object: {},
        __typename: 'DropdownOption',
      },
    ],
    VALIDATIONS_PO: {
      upiID: (text: string) => /^[a-zA-Z0-9@]*$/.test(text) && (text.match(/@/g) || []).length <= 1,
      acNumber: (text: string) => /^[a-zA-Z0-9]*$/.test(text),
      bankName: (text: string) => /^[a-zA-Z ]*$/.test(text),
      acHolderName: (text: string) => /^[a-zA-Z ]*$/.test(text),
      ifscCode: (text: string) => /^[a-zA-Z0-9]*$/.test(text),
    },
    PILLS_GROUP_ARRAY: ['500', '1000', '2000', '5000'],
    ACTION_REQUEST_HEADER: ['dealerName', 'evdNumber', 'transferredAmount', 'requestDate', 'actions'],
    ACTION_CARD_DETAILS: [{ key: 'dealerName' }, { key: 'evdNumber' }, { key: 'transferredAmount' }, { key: 'requestDate' }],
  },
  AD_LOGIN: ['openid', 'profile', 'email'],
  AD_SCOPE: ['openid', 'profile', 'email', 'offline_access', 'User.Read'],
  QUOTATION: {
    CONNECTION_TYPE: [
      { text: 'Continue with Existing Box', value: 'existingBox' },
      { text: 'Change the Box Type', value: 'change' },
    ],
  },
  STATUS_OPTIONS: {
    STATUS: [
      {
        id: 'Open',
        name: 'Open',
      },
      {
        id: 'Closed',
        name: 'Closed',
      },
      {
        id: 'Cancelled',
        name: 'Cancelled',
      },
      {
        id: 'Pending',
        name: 'Pending',
      },
      {
        id: 'Close Looping',
        name: 'Close Looping',
      },
      {
        id: 'All',
        name: 'All',
      },
    ],
  },
};
