export const STRINGS = {
  MOBILE_AGENT: 'tpSales/mobileApp',
  WEB_AGENT: 'tpSales/website',
  TOKEN: 'token',
  REDIRECTION_ID: 'redirectionId',
  REDIRECTION_TOKEN: 'redirectionToken',
  APOLLO_ERROR: 'ApolloError',
  REALM_KEY: 'Sales',
  PERSISTENT_KEY: 'root',
  PERSISTENT_REDIRECTION_KEY: 'rootRedirection',
  PERSISTENT_ACCOUNT_INFORMATION_KEY: 'rootAccountInformation',
  PERSISTENT_PRIMARY_TV_KEY: 'rootPrimaryTvRegistration',
  PERSISTENT_ETSK_REG_KEY: 'rootETskRegistration',
  PERSISTENT_ETSK_REG_SCHEDULER_KEY: 'rootETskRegistrationScheduler',
  BOX_UPGRADE_KEY: 'rootBoxUpgradation',
  BOX_TYPE_CHANGE_KEY: 'rootBoxTypeChange',
  QUOTATION_KEY: 'rootQuotation',
  PERSISTENT_EXCLUSIVE_STORE: 'rootExclusiveStore',
  PERSISTENT_TSK_VOUCHER: 'rootTskVoucher',
  PERSISTENT_PURCHASE_ORDER: 'rootPurchaseOrder',
  PERSISTENT_TRANSACTION_HISTORY_KEY: 'rootTransactionHistory',
  PERSISTENT_FORM_KEY: 'rootForm',
  PERSISTENT_COMMON: 'rootCommon',
  PERSISTENT_CUSTOMER_OFFER_KEY: 'rootCustomerOffer',
  PERSISTENT_RECHARGE_WINBACK_KEY: 'rootRechargeWinback',
  PERSISTENT_PARTNER_APPROVAL_KEY: 'rootPartnerApproval',
  PERSISTENT_EVD_BALANCE_INFO_KEY: 'rootEvdBalanceInfo',
  PERSISTENT_LANGUAGE_KEY: 'rootLanguage',
  PERSISTENT_INVOICE_KEY: 'rootInvoice',
  PERSIST_ACTIVATION_STATUS_KEY: 'rootActivationStatus',
  PERSISTENT_MODIFY_PACK_KEY: 'rootModifyPack',
  PERSISTENT_DEALER_STOCK_KEY: 'rootDealerStock',
  PERSISTENT_STORE_DASHBOARD_KEY: 'rootStoreDashboard',
  TOKEN_KEY: 'tokenKey',
  ACCESS_TOKEN: 'accessToken',
  REFRESH_TOKEN: 'refreshToken',
  ACCESS_EXPIRY: 'accessExpiry',
  REFRESH_EXPIRY: 'refreshExpiry',
  PERSIST_ROOT_KEY: 'persist:root',
  TEXT: 'text',
  ICON_FORMATTER: 'icon_formatter',
  VALIDATE_NUMBER: 'validate_number',
  DELETE_ROW: 'delete_row',
  ACTIVE: 'Active',
  PENDING: 'Pending',
  USER_GUIDE: 'userGuide',
  TRAINING_VIDEO: 'trainingVideo',
  EMPTY_PACKAGE_INFO_COLLECTION: 'emptyPackageInfoCollection',
  EMPTY_FAQ_COLLECTION: 'emptyFaqCollection',
  INTERNAL_SERVER_ERROR: 'internalError',
  REDIRECTION_ERROR: 'redirectionError',
  REDIRECTION_LOGIN: 'RedirectionLogin',
  LOGIN: 'Login',
  COOKIE: 'cookie',
  AUTH: 'auth',
  NAME: 'name',
  DEALER_ID: 'dealerID',
  MOBILE_NUMBER_IN_HEADER: 'mobileNoInHeader',
  VERSION: 'v666',
  USER: 'user',
  COMMON: 'common',
  UI: 'ui',
  DROPDOWN_HOVER_ID: 'dropdownHoverId',
  BUTTON_HOVER_ID: 'buttonHoverId',
  REQUEST_SUCCESSFUL: 'requestSuccessFul',
  TRANSECTION_ID: 'transactionID',
  name: 'name',
  X_AXIS: 'xAxis',
  Y_AXIS: 'yAxis',
  PARAMETER: 'parameter',
  FILTER_BY_PARAMETER: 'filterByParam',
  FILTERS: 'Filters',
  CONFIRMATION: 'confirmation',
  PROCEED: 'proceed',
  PROCEED_TO_CHANGE: 'proceedToChangeEvdMdn',
  channelPackPrice: 'channelPackPrice',
  channels: 'channels',
  SUCCESS: 'SUCCESS',
  SENTTO: 'sentTo',
  SENTTORMN: 'sentToRmn',
  BACKSPACE: 'Backspace',
  OTP_ERROR: 'otpError',
  STATUS_TEXT: 'statusText',
  CENTERED_TEXT: 'centeredText',
  LEFT_ALIGNED_TEXT: 'leftAlignedText',
  STATUS: 'status',
  ADD: 'add',
  UPDATE: 'update',
  DELETE: 'delete',
  YES: 'Y',
  NO: 'N',
  DEACTIVATED: 'Deactivated',
  WITHOUT_RECHARGE: 'withoutRecharge',
  ACTION_MDN: 'actionMdn',
  TRACK_MDN: 'trackMdn',
  TRACK_EVD_MDN_CHANGE: 'trackEvdMdnChange',
  APPROVED: 'approved',
  APPROVED_CAPS: 'Approved',
  REJECTED: 'rejected',
  REJECTED_CAPS: 'Rejected',
  MDN_CHANGE_APPROVE: 'mdnChangeApprove',
  MDN_CHNAGE_REJECT: 'mdnChangeReject',
  MDN: 'mdn',
  UPDATED_NEW_MDN: 'updatedNewMdn',
  REASON_FOR_REJECTION: 'reasonForRejection',
  SEARCH_LOCALLY: 'searchLocally',
  MIXPANEL_ID: 'distinctid',
  NAVIGATION_HISTORY_KEY: 'navigationHistory',
  DYNAMIC_QUERY: 'dynamicQuery',
  ERROR_OCCURED_WHILE_FETCHING_DATA: 'Error occurred while fetching data:',
  DISTRIBUTOR: 'distributor',
  DSR: 'dsr',
  SELF: 'self',
  DEVICE_DETAILS: 'device_details',
  USER_LOGOUT: 'user/logout',
  DELETE_AUTO_EVD_TRANSFER: 'deleteAutoEvdTransfer',
  RESET_FIELDS: 'resetFields',
  CUSTOM_DATE_RANGE: 'customDateRange',
  MULTI_SHOW_HIDE: 'multiShowHide',
  ALL: 'All',
  SUBSCRIBER: 'subscriber',
  NA: 'NA',
  PARTNER_ROLE: 'Partner – Role',
  SUPPLY_INFORMATION: 'Supply Information',
  MAXIMUM_STOCK: 'Maximum Stock',
  CURRENT_STOCK: 'Current stock',
  CONSUMPTION_INFO: 'Consumption Info',
  MATERIAL_LIST: 'Material list',
  AVERAGE_DAILY_RECHARGE: 'avgDailyRecharge',
  LANG: 'lang',
  RAISE_ANOTHER_FEEDBACK: 'raiseAnotherFeedback',
  TRACK_FEEDBACK: 'trackFeedback',
  MATCH_DEPENDENCY: 'matchDependency',
  KINDLY_RECHARGE: 'Kindly recharge your balance!',
  UNKNOWN: 'unknown',
  SELECT_DEALER: 'selectDealer',
  LANGUAGE: 'language',
  LANGUAGES: 'Languages',
  GENRES: 'Genres',
  BOX_TYPE: 'Box Type',
  UNKNOWN_LANGUAGE: 'Unknown Language',
  EN: 'en',
  HOTEL_SUBSCRIPTION: 'hotelSubscription',
  APP_LANGUAGE: 'appLanguage',
  ENGLISH: 'english',
  SAVE_TV_BILL: 'SaveTVBill',
  FALSE: 'false',
  BANGLA: 'Bangla',
  BENGALI: 'Bengali',
  ORIYA: 'Oriya',
  ODIA: 'Odia',
  SUBSCRIBER_INFO: 'subscriberInfo',
  SUBSCRIBER_ID: 'subscriberId',
  ACCOUNT_STATUS_FILTER: 'accountStatusFilter',
  BOX_TYPE_FILTER: 'boxTypeFilter',
  HERE_IS_YOUR_CSV: 'Here is your CSV file',
  FILE_DOWNLOADED_SUCCESSFULLY: 'File downloaded successfully',
  STORAGE_PERMISSION_DENIED: 'Storage permission denied',
  AZ_ALPHABETICAL: 'AZ Alphabetical',
  HIGH_TO_LOW: 'High to low in hand stock',
  LOW_TO_HIGH: 'Low to high in hand stock',
  FETCH_CHILD_PARTNER_DETAILS: 'fetchChildPartnerDetails',
  NAME_NT: 'nameNT',
  PUNJABI: 'Punjabi',
  PA: 'pa',
  PK: 'PK',
  RC: 'RC',
  sdChannels: 'sdChannels',
  hdChannels: 'hdChannels',
  VALIDATE: 'pleaseValidateAboveDetails',
  SUBMIT: 'submit',
  HINDI: 'Hindi',
  GUJARATI: 'Gujarati',
  KANNADA: 'Kannada',
  MALAYALAM: 'Malayalam',
  MARATHI: 'Marathi',
  TAMIL: 'Tamil',
  TELUGU: 'Telugu',
  ROW_CONTAINER: 'rowContainer',
  INVALID: '__INVALID__',
  TOGGLE_ACCORDION: 'toggleAccordion',
  HD: 'HD',
  SD: 'SD',
  STANDARD: 'Standard',
  UNDEFINED: 'undefined',
  FAILED: 'Failed to fetch report',
  WINBACK_RECHARGED: 'winBackRecharged',
  SENT_TO_PARTNER_NUMBER: 'sentToPartnerNumber',
  DEALER_FEEDBACK: 'dealerFeedback',
  DURATION: 'Duration',
  OFFER_TYPE: 'Offer type',
  OFFER_NAME: 'Offer name',
  NEW_CUSTOMER_OFFER_PACKS: 'New customer offers pack',
  EVD: 'EVD',
  WO_NUMBER: 'woNumber',
  HIDE_IN_MOBILE: 'hideInMobile',
  CATEGORY_DROPDOWN: 'categoryDropdown',
  DURATION_DROPDOWN: 'durationDropdown',
  PILLS: 'pills',
  NEW_CUSTOMER_BEST_OFFERS: 'New Customer Best Offers',
  TATAPLAY_BOUQUETS_CATEGORY: 'Tataplay Bouquets Category',
  BROADCASTER_BOUQUETS_CATEGORY: 'Broadcaster Bouquets Category',
  ALACARTE_CHANNEL_CATEGORY: 'Alacarte Channel Category',
  BINGE_PLUS_CATEGORY: 'Binge Plus Category',
  HIDE_IN_WEB: 'hideInWeb',
  DO_GET_BINGE_PLUS_PACKS: 'dogetBingeplusPacksETSK',
  DO_GET_PACKS: 'doGetPacksETSK',
  DO_GET_RENTAL_PACKS: 'doGetRentlPackETSK',
  GET_PACKAGES_URL_TRAI: 'getPackagesURLsTrai',
  SONU: 'Sonu',
  RECHARGE_AMOUNT: 'Recharge Amount',
  SET_UP_BOX: 'Set Top Box',
  BINGE_PLUS: 'Binge+',
  INVOICE: 'Invoice',
  DOWNLOAD_INVOICE: 'Download Invoice',
  TRANSACTION_ID: 'Transaction ID',
  TA: 'ta',
  GET_WO_PACKS: 'getWoPacks',
  MONTHLY: 'Monthly',
  GET_WO_RENTAL_PACK: 'getWoRentalPack',
  ARE_YOU_SURE_WANT_TO_APPROVE_REQUEST: 'areYouSureYouWantToApproveRequest',
  ISP_CODE: 'ispCode',
  FIX_LENGTH: 'fixLength',
  TOWN_LOCALITY: 'townLocality',
  PER_MONTH: 'Per Month',
  WO_INFORMATION: 'WOAndOtherDetails',
  PACKAGE_INFORMATION: 'packagesInformation',
  RECHARGE_TRANSACTION: 'rechargeTransactions',
  ETSK_OFFER: 'etskOffer',
  newConnectionCreated: 'newConnectionCreated',
  multiTvNewConnection: 'multiTvNewConnection',
  BUILDING: 'building',
  ISP_MOBILE_KEY: 'ispMobileKey',
  ASI_MOBILE: 'asiMobile',
  WO_DETAILS: 'Work Order Details',
  OTHER_DETAILS: 'Other Details',
  UPGRADE_WO: 'Upgrade WO Details',
  CHNAGE_TBL: 'changeTbl',
  OUTLET_TYPE: 'outletType',
  ACTIVATION_STATUS: 'activationStatus',
  BCP_ACTIVATION_STATUS: 'bcpActivationStatus',
  Filters: 'filters',
  cart: 'cart',
  BASIC_PACKS: 'BasicPacks',
  HIDE: 'hide',
  LDP: 'LDP',
  DM: 'DM',
  odia: 'odia',
  DL: 'DL',
  RECHARGE_AMOUNT_FIELD: 'rechargeAmount',
  POST: 'POST',
  RECOMENDATION_PARAM: 'recomendationParam',
  monthly: 'monthly',
  annual: 'annual',
  semi: 'semi',
  MISSING_BINGE_PLUS: 'MISSING_BINGE_PLUS',
  BOTH_PRESENT: 'BOTH_PRESENT',
  OK: 'OK',
  NEWEST: 'newest',
  REPUSH_ORDER: 'RepushOrder',
  LESS_STOCK_IN_HAND: 'lessStockInHand',
  GREATER_STOCK_IN_HAND: 'greaterStockInHand',
  VALD_ERROR_POPUP: 'validationErrorPopup',
  NETWORK: 'network',
  DIS_DIRECTLY_MAPPED_TO_CSM: 'Distributors directly mapped to CSM ',
  AMOUNT: 'amount',
  CREDIT_AMOUNT: 'creditAmount',
  BONUS_AMOUNT: 'bonusAmount',
  HTTP: 'http',
  PINK_ICON: 'pinkIcon',
  COUNT_ZERO: '0',
  DATE_FORMAT: 'en-GB',
  STORE_REPORT: 'Store_Operational_Report_',
  ELIGIBLE: 'Eligible',
  DEBIT_AMOUNT: 'debitAmount',
  STRING: 'string',
  PICTURE_QUALITY: 'Picture Quality',
  ANDROID: 'Android',
  INVALID_MOBILE: 'Invalid mobile no.',
  tskValue: 'tskValue',
  USER_DETAILS: 'userDetails',
  TRUE: 'true',
  BOX_UPGRADE_SUCCESS: 'boxUpgradeSuccess',
  BOX_UPGRADE_FAILURE: 'boxUpgradeFailureMsg',
  SELECT_BINGE_OFFER: 'Select Binge Plus Category',
  ZERO: '0',
  BOX: 'Box',
  MOBDESKTOP: 'MOBDESKTOP',
  INDIA: 'India',
  RechNo: 'RechNo',
  USERNAME: 'userName',
  SECONDARY_CONNECTION: 'Secondary Connection',
  ACTIVATION_MARGIN: 'Activation Margin',
  ADDITIONAL_ACTIVATION_MARGIN: 'Additional Activation Margin',
  CREDIT_FOR_BINGE_ADD_PACK_BOUNS: 'Credit for binge add pack bonus',
  BINGE_PACK_ADDITION_MARGIN: 'Bing Pack Addition Margin',
  UPP_BASED_RECHARGE: 'UPP based recharge',
  UPP_WINGACK_PACK_ADDITION_MARGIN: 'UPP/ Winback Pack Addition Margin',
  WINBACK_CAMPAIGN_MARGIN: 'Winback Campaign margin',
  METSK_CAMPAIGN_MARGON: 'METSK Campaign margin',
  REFUND_OF_CONSUMED_TSK: 'Refund of Consumed TSK',
  A_STAR: 'A Star',
  EASY_FORM: 'Easy Form',
  OTHERS: 'Others',
  OTHERS_LOWER: 'others',
  WORK_ORDER_CREATED: 'woCreated',
  UNSCHEDULED: 'Unscheduled',
  ANNUAL: 'Annual',
  SEMI_ANNUAL: 'Semi-Annual',
  NOT_AVAILABLE: 'Not available',
  All: 'all',
  CALENDAR_FORMAT: 'en-US',
  HIDE_IN_MOB: 'hideInMob',
  TO_RIGHT: 'to right',
  TO_LEFT: 'to left',
  TO_TOP: 'to top',
  TO_BOTTOM: 'to bottom',
  COMMISSIONS: 'commissions',
  MONTH: 'month',
  BINGE_OFFER: 'bingeOffer',
  BINGE_RECHARGE_VALUE: 'bingeRechargeValue',
  SR: 'sr',
  PRIMARY_TV_REGISTRATION: 'Primary TV registration',
  MULTI_TV_REGISTRATION: 'Multi TV registration',
  ETSK_REGISTRATION: 'eTSK registration',
  CUSTOMER_DETAILS_PINCODE: 'customerDetailsPinCode',
  NUMBER_OF_CONNNECTIONS: 'numberOfConnections',
  CUSTOMER_DETAILS_OFFER_TYPE: 'customerDetailsOfferType',
  SUBSCRIBER_RMN: 'subscriberRmn',
  SUBSCRIBER_EMAIL: 'subscriberEmail',
  WO_STATUS: 'WoStatus',
  WO_RECREATION: 'WO_RECREATION',
  YES_LOWER: 'yes',
  ROLE_OUTLET_TYPE: 'role/outletType',
  MORE_DETAILS: 'moreDetails',
  PREMIUM_PACKAGE: 'Premium Package',
  NEW_CONNECTION: 'New Connection',
  RECHARGE: 'Recharge',
  SERVICE_COMPLAINT: 'Service Complaint',
  ENQUIRY_NEW_CONNECTION: 'Enquiry of New Connection',
  ENQUIRY_PACK: 'Enquiry of Pack',
  SALES_VAS: 'Sales of VAS',
  BOX_UPGRADE: 'Box Upgrade',
  GENERAL_ENQUIRY: 'General Enquiry',
  WALK_IN: 'Walk-In',
  OVER_THE_PHONE: 'Over the Phone',
  TELE_CALLING: 'Tele-calling',
  OUTBOUND_ACTIVITY: 'Outbound Activity',
  SPECIAL_COMMENTS: 'Special Comments',
  CUSTOMER_DEMO: 'CustomerDemo',
  DATE_INPUT: 'dateInput',
  DASHBOARD: 'dashboard',
  BOOLEAN: 'Boolean',
  CHECKBOX: 'Checkbox',
  TEXT_INPUT: 'TextInput',
  ANSWERS: 'answers',
  MOBILE_NUMBER: 'mobileNumber',
  EXITSING_BOX: 'existingBox',
  MULTI_TV: 'multiTVConnection',
  MULTI_TV_CONNECTION_TYPE: 'multiTVConnectionType',
  RECHARGES: 'Recharges',
  BALANCE_TRANSFER: 'Balance Transfer',
  BALANCE_TRANSFER_LOWER: 'balance transfer',
  REVERSALS: 'Reversals',
  REVERSAL_LOWER: 'reversal',
  REVERSE_LOWER: 'reverse',
  EVD_WALLET: 'EVD Wallet',
  OTF_CREDITS: 'OTF Credits',
  CREDIT: 'Credit',
  DEBIT: 'Debit',
  TSK_NO: 'tskNo',
  EXIST: 'exist',
  CONNECTION_PROVIDER: 'connectionProvider',
  RESIDENTIAL: 'Residential',
  MULTI: 'Multi',
  SELECT_BOX_TYPE: 'Select Box Type',
  MULTIPLE_RMN: 'MULTIPLE_RMN',
  REJECT: 'reject',
  APPROVE: 'approve',
  AZURE_AD: 'AzureAD',
  IS_AD: 'isAD',
  SESSION_STORAGE: 'sessionStorage',
  AD_PROMT: 'select_account',
  BANK: 'Bank',
  PRODUCT: 'PRODUCT',
  FOS_REJECTION_REASON: 'FosRejectionReason',
  BINGE_EVD_TRANSACTION: 'Binge EVD Transaction',
  FAILURE: 'FAILURE',
  UNREGISTERED: 'Un-Registered',
  GST_UNREGISTERED: 'gstUnregistered',
  GST_UPDATED_SUCCESSFULLY: 'gstUpdatedSuccessfully',
  EVD_PAYMENT: 'EVD PAYMENT',
  ANNUAL_WINBACK_OFFER: 'annualWinbackOffer',
  SEMI_ANNUAL_WINBACK_OFFER: 'semiAnnualWinbackOffer',
  QUARTER_WINBACK_OFFER: 'quarterWinbackOffer',
  DEALER_MARGIN_ANNUAL: 'dealerMarginAnnual',
  DEALER_MARGIN_SEMI: 'dealerMarginSemi',
  DEALER_MARGIN_QUARTER: 'dealerMarginQuarter',
  DEALER_WHATSAPP: 'dealerWhatsapp',
  ETSK: 'ETSK',
  PYSICAL_TSK: 'PhysicalTsk',
  DATE_FILTER: 'dateFilter',
  DHAMAKA: 'Dhamaka',
};

export const PLATFORM = {
  WEB: 'web',
  ANDROID: 'android',
  IOS: 'ios',
  IPAD_OS: 'iPadOS',
  I_OS: 'iOS',
};

export const DROPDOWN = {
  SELECT: 'Select',
};
export const SCANNER_FORMATS = ['qr', 'ean-13'];

export const FORMS = {
  trackRequest: 'trackRequest',
  raiseRequest: 'raiseRequest',
  heavyRefresh: 'heavyRefresh',
  customerRecharge: 'customerRecharge',
  rechargeReversal: 'rechargeReversal',
  customerInformation: 'customerInformation',
  tskRefund: 'tskRefund',
  changeEVDPin: 'changeEVDPin',
  checkRmnUpdate: 'checkRmnUpdate',
  rmnUpdate: 'rmnUpdate',
  packageInformation: 'packageInformation',
  transectionHistory: 'transectionHistory',
  evdMdnChange: 'evdMdnChange',
  modifyPack: 'modifyPack',
  faq: 'faq',
  demoBoxDetail: 'demoBoxDetail',
  menus: 'menus',
  forms: 'forms',
  demoBoxDetails: 'demoBoxDetails',
  rechargeWinback: 'rechargeWinback',
  securityCheck: 'securityCheck',
  winBackSecurityCheck: 'winBackSecurityCheck',
  evdMdnChangeReason: 'evdMdnChangeReason',
  customerOffersSubIdList: 'customerOffersSubIdList',
  customerOffers: 'customerOffers',
  winBackMonthlyRecharge: 'winBackMonthlyRecharge',
  trackTsraRequest: 'trackTsraRequest',
  tsraInventory: 'tsraInventory',
  customerInvoice: 'customerInvoice',
  trackDealerFeedback: 'trackDealerFeedback',
  filterTsraInventory: 'filterTsraInventory',
  gstDetails: 'gstDetails',
  viewMyTeamDetails: 'viewMyTeamDetails',
  rechargeDetails: 'rechargeDetails',
  createChannelPartner: 'createChannelPartner',
  viewNewDealers: 'viewNewDealers',
  viewNewDealer: 'viewNewDealer',
  primaryTvRegistration: 'primaryTvRegistration',
  woRecreation: 'woRecreation',
  woRechargeDetails: 'woRechargeDetails',
  primaryRechargeDetails: 'primaryRechargeDetails',
  trackPartnerRequest: 'trackPartnerRequest',
  proceedToRecharge: 'proceedToRecharge',
  proceedToOffer: 'proceedToOffer',
  multiTvRegistration: 'multiTvRegistration',
  activationStatusSubIdList: 'activationStatusSubIdList',
  activationStatus: 'activationStatus',
  dealerStock: 'dealerStock',
  filterDealerStock: 'filterDealerStock',
  createNewDealer: 'createNewDealer',
  createDealerStock: 'createDealerStock',
  woRecreationSubIdList: 'woRecreationSubIdList',
  eTSKMultiTv: 'eTSKMultiTv',
  eTSKMultiTvSubIdList: 'eTSKMultiTvSubIdList',
  etskMultiTvRechargeDetails: 'etskMultiTvRechargeDetails',
  eTSKRepush: 'eTSKRepush',
  eTSKRepushSelPacks: 'eTSKRepushSelPacks',
  eTSKRepushRechargeDetails: 'eTSKRepushRechargeDetails',
  multiTvRechargeDetails: 'multiTvRechargeDetails',
  eTSKMultiTvRepush: 'eTSKMultiTvRepush',
  eTSKMultiTvRepushSubIdList: 'eTSKMultiTvRepushSubIdList',
  partnerApprovalRejectReasons: 'partnerApprovalRejectReasons',
  modifyPackSubIdList: 'modifyPackSubIdList',
  myEvdBalance: 'myEvdBalance',
  configureDeatils: 'configureDeatils',
  demoAccount: 'demoAccounts',
  eTSKRegistration: 'eTSKRegistration',
  registrationDetails: 'registrationDetails',
  createChannelPartnerFos: 'createChannelPartnerFos',
  createChannelPartnerAd: 'createChannelPartnerAd',
  storeDashboard: 'storeDashboard',
  storeOperationalDetails: 'storeOperationalDetails',
  multiTvSubIdList: 'multiTvSubIdList',
  boxUpgrade: 'boxUpgrade',
  selectExitingBox: 'selectBox',
  proceedWithRecharge: 'boxUpgradeRechargeDetails',
  existingWorkOrder: 'existingWorkOrderDetails',
  boxUpgradeSubIdList: 'boxUpgradeSubIdList',
  boxTypeChangeRMN: 'rmnBoxTypeChange',
  boxtypeSubIDList: 'boxTypeChangeSubIdList',
  selectExitsingBoxType: 'selectExistingBox',
  existingWorkOrderDetailsBoxTypeChange: 'existingWorkOrderDetailsBoxTypeChange',
  boxTypeChangeRechargeDetails: 'boxTypeChangeRechargeDetails',
  competitorDataCapture: 'competitorDataCapture',
  addMoreCompetitorData: 'addMoreCompetitorData',
  dashboard: 'dashboard',
  quotation: 'quotation',
  quotationETSKPincode: 'quotationETSKPincode',
  quotationMultiTVRMN: 'quotationMultiTVRMNModal',
  quotationETSKSendQuote: 'quotationETSKSendQuote',
  quotationMultiTVsubIDList: 'quotationMultiTVSubIdList',
  quotationMultiTVMobEmailModal: 'quotationMultiTVMobEmailModal',
  quotationPrimaryPincode: 'quotationPrimaryPincode',
  quotationPrimarySendQuote: 'quotationPrimarySendQuote',
  walkInDetails: 'walkinDetails',
  walkinDetailsLead: 'walkinDetailsLead',
  teleCallingDetails: 'teleCallingDetails',
  outBoundDetails: 'outBoundDetails',
  outboundDetailsLead: 'outboundDetailsLead',
  overThePhoneDetails: 'overThePhoneDetails',
  serviceComplaintLead: 'serviceComplaintLead',
  salesOfValueLead: 'salesOfValueLead',
  rechargeLead: 'rechargeLead',
  packEnquiryDetails: 'packEnquiryDetails',
  newConnectionDetails: 'newConnectionDetails',
  generalEnquiryLead: 'generalEnquiryLead',
  newConnectionEnquiryDetails: 'newConnectionEnquiryDetails',
  boxUpgradeDetailsLead: 'boxUpgradeDetailsLead',
  tskVoucher: 'tskVoucher',
  boxUpgradeDetailsLeadWithoutDemo: 'boxUpgradeDetailsLeadWithoutDemo',
  newConnectionEnquiryDetailsWithoutDemo: 'newConnectionEnquiryDetailsWithoutDemo',
  generalEnquiryLeadWithoutDemo: 'generalEnquiryLeadWithoutDemo',
  newConnectionDetailsWithoutDemo: 'newConnectionDetailsWithoutDemo',
  packEnquiryDetailsWithoutDemo: 'packEnquiryDetailsWithoutDemo',
  rechargeLeadWithoutDemo: 'rechargeLeadWithoutDemo',
  salesOfValueLeadWithoutDemo: 'salesOfValueLeadWithoutDemo',
  serviceComplaintLeadWithoutDemo: 'serviceComplaintLeadWithoutDemo',
  manageApps: 'manageApps',
  manageAppsSubIdList: 'manageAppsSubIdList',
  rejectTsra: 'rejectTsra',
  approveTsra: 'approveTsra',
  openEVDForm: 'openEVDForm',
  openMaterialsForm: 'openMaterialsForm',
  purchaseOrderTrackDetails: 'purchaseOrderTrackDetails',
  purchaseOrderTrackDetailsASM: 'purchaseOrderTrackDetailsASM',
  purchaseOrderSettelmentsTable: 'purchaseOrderSettelmentsTable',
  purchaseOrderTrackPOSM: 'purchaseOrderTrackPOSM',
  purchaseOrderTrackDetailsDealer: 'purchaseOrderTrackDetailsDealer',
  purchaseOrderTrackDetailsFos: 'purchaseOrderTrackDetailsFos',
  openMaterialsFormFos: 'openMaterialsFormFos',
  purchaseOrderRejectReasons: 'purchaseOrderRejectReasons',
  tskCancellation: 'tskCancellation',
  validateTskCancellation: 'validateTskCancellation',
  slabList: 'slab_list',
  quotationChangeBox: 'quotationChangeBox',
  trasactionDetailsEVD: 'trasactionDetailsEVD',
  otfDetailsEVD: 'otfDetailsEVD',
  balanceTransferTable: 'balanceTransferTable',
  consolidatedTransaction: 'consolidatedTransactionTable',
  productDetailsPO: 'productDetailsPO',
  openEVDFormASM: 'openEVDFormASM',
  openMaterialsFormASM: 'openMaterialsFormASM',
  gstDetailsProfile: 'gstDetailsProfile',
  dealerHelp: 'dealerHelp',
  dealerRaiseRequest: 'dealerRaiseRequest',
  dealerTrackRequest: 'dealerTrackRequest',
  dealerHelpTrackTable: 'dealerHelpTrackTable',
  demoAccountEtsk: 'demoAccountEtsk',
  bingeDashboardTable: 'bingeDashboardTable',
};

export const LANGUAGES = [
  { key: 'en', value: 'English' },
  { key: 'hi', value: 'Hindi' },
  { key: 'ta', value: 'Tamil' },
  { key: 'ml', value: 'Malayalam' },
  { key: 'bn', value: 'Bengali' },
];

export const DRAWER_ITEMS = [
  { id: 'language', name: 'languageSettings' },
  { id: 'password', name: 'changePassword' },
  { id: 'logout', name: 'logout' },
];

export const DRAWER_OPTIONS = {
  LANGUAGE: 'language',
  PASSWORD: 'password',
  LOGOUT: 'logout',
};

export const EXCLUDED_PAGE_HEADERS = ['Dashboard', 'Login'];

export const EXCLUDED_OPERATIONS = ['Login', 'RedirectionInfo', 'RefreshToken', 'Logout'];

export const INCLUDE_OPERATION = ['RefreshToken'];

export const ROUTE = {
  MOBILE: {
    LOGIN: 'Login',
    DASHBOARD: 'Dashboard',
    HOME: 'Home',
    ERROR: 'Error',
    FAQ: 'FAQ',
    MY_ACTION: 'My Actions',
    TRANSACTION: 'Transaction',
    LOGIN_OTP_VER: 'LoginOtpVer',
    LOCAL_AUTHENTICATION: 'LocalAuthentication',
  },
  WEB: {
    DEFAULT: '/',
    LOGIN: 'login',
    HOME: 'home',
    CONFIRM_REVERSAL: 'confirmReversal',
    ERROR: 'error',
    CUSTOMER_DETAILS: 'customerDetails',
    CUSTOMER_RECHARGE: 'customerRecharge',
    CUSTOMER_SERVICE: 'customerService',
    CHECK_RMN_UPDATE: 'checkRmnUpdate',
    RECHARGE_REVERSAL: 'rechargeReversal',
    TRANSACTION_HISTORY: 'transactionHistory',
    TRANSACTION: 'transaction',
    INVOICE_TRANSACTION: 'invoiceTransactions',
    EVD_MDN_CHANGE_SUCCESS: 'evdMdnChangeSuccess',
    HEAVY_REFRESH: 'heavyRefresh',
    EVD_TRANSFER: 'evdTransfer',
    EVD_TRANSFER_ASM: 'evdTransferAsm',
    UPDATE_AUTO_EVD: 'updateAutoEvd',
    SET_AUTO_EVD: 'setAutoEvd',
    RESET_EVD_PIN: 'resetEVDPin',
    BINGE_VIEW_DETAILS: 'bingeViewDetails',
    PACK_VIEW_DETAILS: 'packViewDetails',
    MY_OFFERS_VIEW_DETAILS: 'myOffersViewDetails',
    ETSK_OFFERS_VIEW_DETAILS: 'etskOfferViewDetails',
    ETSK_REPUSH_OFFERS_VIEW_DETAILS: 'etskRepushOfferViewDetails',
    CUSTOMER_RECHARGE_VIEW_DETAILS: 'customerRechargeViewDetails',
    RECHARGE_WIN_BACK_VIEW_DETAILS: 'rechargeWinBackViewDetails',
    CHANGE_EVD_PIN: 'changeEVDPin',
    DEMO_BOX_DETAIL: 'demoBoxDetail',
    DEMO_BOX_DETAILS: 'demoBoxDetails',
    RECHARGE_WIN_BACK_OFFERS: 'rechargeWinbackOffers',
    AUTO_EVD_TRANSFER: 'autoEvdTransfer',
    FILTER_EVD_MDN_CHANGE: 'filterEvdMdnChange',
    EVD_MDN_APPROVE_OR_REJECT: 'evdMdnAppOrRej',
    EVD_MDN_DISTRIBUTER_SUCCESS: 'evdMdnDistSuccess',
    CUSTOMER_OFFERS: 'customerOffers',
    CUSTOMER_OFFER_SUCCESS: 'customerOfferSuccess',
    AUTO_EVD_SUCCESS: 'autoEvdSuccess',
    UPDATE_TSRA_ACTION: 'updateTsraAction',
    RECHARGE_WINBACK: 'rechargeWinback',
    TSRA_INVENTORY: 'tsraInventory',
    TSRA_LIFE_CYCLE: 'tsraLifeCycle',
    TRACK_TSRA_ACTION: 'trackTsraAction',
    FILTER_TRACK_TSRA_REQUEST: 'filterTrackTsraRequest',
    CUSTOMER_INVOICE: 'customerInvoice',
    RAISE_DEALER_FEEDBACK: 'raiseDealerFeedback',
    TRACK_DEALER_FEEDBACK: 'trackDealerFeedback',
    DEALER_FEEDBACK_SUCCESS: 'dealerFeedbackSuccess',
    WINBACK_SUCCESS: 'winbackSuccess',
    MANAGE_HIERARCHY_SUCCESS: 'manageHierSuccess',
    VIEW_MY_TEAM_DETAILS: 'viewMyTeamDetails',
    CREATE_CHANNEL_PARTNER: 'createChannelPartner',
    WORK_ORDER_RECREATION: 'woRecreation',
    WORK_ORDER_RECREATION_SUCCEESS: 'woRecreationSuccess',
    ETSK_REGISTRATION_CHANNELS: 'eTSKRegistrationChannels',
    ETSK_REGISTRATION_SUMMARY: 'eTSKRegistrationSummary',
    PRIMARY_TV_REGISTRATION: 'primaryTvRegistration',
    SECONDARY_TSK_REGISTRATION: 'secondaryTskRegistration',
    REGISTRATION_DETAILS: 'registrationDetails',
    PRIMARY_REGISTRATION_CHANNELS: 'primaryRegistrationChannels',
    PRIMARY_REG_OFFERS_DETAILS: 'primaryRegOfferDetails',
    PRIMARY_REGISTRATION_SUMMARY: 'primaryRegistrationSummary',
    ETSK_REG_SUCCESS: 'eTskRegSuccess',
    ETSK_MULTI_TV_SUCCESS: 'eTskMultiTvSuccess',
    ETSK_MULTI_TV_REPUSH_SUCCESS: 'eTskMultiTvRepushSuccess',
    PRIMARY_TV_REG_SUCCESS: 'primaryTvRegSuccess',
    VIEW_NEW_DEALERS: 'viewNewDealers',
    WO_RECREATION_CHANNELS: 'woRecreationChannels',
    WO_RECREATION_SUMMARY: 'woRecreationSummary',
    PARTNER_APPROVAL_DETAILS: 'partnerApprovalDetails',
    ACTION_PARTNER_REQUEST: 'actionPartnerRequest',
    ACTIVATION_STATUS_DETAILS: 'activationStatusDetails',
    RE_PUSH_ORDER_CHANNELS: 'rePushOrderChannels',
    RE_PUSH_ORDER_SUMMARY: 'rePushOrderSummary',
    MULTI_TV_REGISTRATION: 'multiTvRegistration',
    MULTI_TV_REGISTRATION_SUMMARY: 'multiTvSummary',
    RE_PUSH_ORDER_OFFERS_DETAILS: 'rePushOrderOfferDetails',
    DEALER_STOCK: 'dealerStock',
    CREATE_NEW_DEALER_SUCCESS: 'createNewDealerSuccess',
    WO_OFFER_VIEW_DETAILS: 'woRecreationOfferViewDetails',
    ETSK_MULTI_TV: 'eTSKMultiTv',
    ETSK_MULTI_TV_SUMMARY: 'eTSKMultiTvSummary',
    ETSK_REPUSH: 'eTSKRepush',
    ETSK_REPUSH_SEL_PACKS: 'eTSKRepushSelPacks',
    ETSK_REPUSH_SUCCESS: 'eTskRepushSuccess',
    ETSK_REPUSH_CHANNELS: 'eTSKRepushChannels',
    ETSK_REPUSH_SUMMARY: 'eTSKRepushSummary',
    MULTI_TV_SUCCESS: 'multiTvSucess',
    MODIFY_PACK: 'modifyPack',
    RE_PUSH_ORDER_SUCCESS: 'rePushOrderSuccess',
    ACTIVATION_STATUS: 'activationStatus',
    TRACK_PARTNER_REQUEST: 'trackPartnerRequest',
    MULTI_TV_SUMMAARY: 'multiTvSummary',
    PARTNER_APPROVAL_SUCCESS: 'partnerApprovalSuccess',
    OTF_CREDIT_DETAILS: 'otfCreditDetails',
    BALANCE_TRANSFER_DETAILS: 'balanceTransferDetails',
    CONSOLIDATED_TRANSACTION: 'consolidatedTransaction',
    RECHARGE_TRANSACTION: 'rechargeTransaction',
    OTF_CREDIT_DETAILS_FOS: 'otfCreditDetailsFos',
    BALANCE_TRANSFER_dETAILS_FOS: 'balanceTransferDetailsFos',
    CONSOLIDATED_TRANSACTION_FOS: 'consolidatedTransactionFos',
    RECHARGE_TRANSACTION_FOS: 'rechargeTransactionFos',
    DEMO_ACCOUNT: 'demoAccount',
    CONFIRM_REVERSAL_INFO: 'confirmReversalInfo',
    CONFIRM_REVERSAL_INFO_FOS: 'confirmReversalInfoFos',
    EVD_BALANCE_INFO: 'evdBalanceInfo',
    STORE_DASHBOARD: 'storeDashboard',
    SELECT_CHECKLIST: 'selectChecklist',
    BOX_UPGRADE: 'boxUpgrade',
    SELECT_NEW_BOX: 'selectNewBox',
    CONFIRM_DETAILS: 'confirmDetails',
    BOX_UPGRADE_SUCCESS: 'boxUpgradeSuccess',
    BOX_TYPE_CHANGE: 'boxTypeChange',
    SELECT_BOX_TYPE: 'selectBoxType',
    BOX_TYPE_CHANNELS: 'boxTypeChannels',
    BOX_TYPE_SUMMARY: 'boxTypeSummary',
    BOX_TYPE_MULTI_TV_SUMMARY: 'boxTypeMultiTVSummary',
    BOX_TYPE_SUCCESS: 'boxTypeSuccess',
    COMPETITOR_DATA_CAPTURE: 'competitorDataCapture',
    COMPETITOR_DATA: 'competitorData',
    BOX_TYPE_CHANGE_DETAILS: 'boxtypeChangeViewDetails',
    OTHER_CUSTOMER_ACTIONS: 'customerActions',
    REGISTER_NEW_CUSTOMER: 'registerNewCustomer',
    MY_COMMISSIONS: 'myCommissions',
    NOTIFICATIONS: 'notifications',
    DEMO_ACCOUNT_SUCCESS: 'demoAccountSuccess',
    ACT_STATUS_PACK_DETAILS: 'activationStatusPackDetails',
    LOGIN_OTP_VER: 'LoginOtpVer',
    QUOTATION: 'quotation',
    QUOTATION_ETSK_CHANNELS: 'quotationETSKChannels',
    QUOTATION_ETSK_SUMMARY: 'quotationETSKSummary',
    QUOTATION_ETSK_SUCCESS: 'quotationETSKSuccess',
    ETSK_REGISTRATION: 'eTSKRegistration',
    QUOTATION_MULTITV_SUMMARY: 'quotationMultiTVSummary',
    QUOTATION_MULTITV_SELECTION: 'quotationMultiTVSelection',
    QUOTATION_MULTITV_SUCCESS: 'quotationMultiTVSuccess',
    QUOTATION_PRIMARY_CHANNELS: 'quotationPrimaryChannels',
    QUOTATION_PRIMARY_SUMMARY: 'quotationPrimarySummary',
    QUOTATION_PRIMARY_SUCCESS: 'quotationPrimarySuccess',
    QUOTATION_ETSK_PACK_DETAILS: 'quotationETSKPackDetails',
    DEALER_STOCK_LIST: 'dealerStockList',
    QUOTATION_ETSK_OFFER: 'quotationETSKOffer',
    QUOTATION_PRIMARY_OFFER: 'quotationPrimaryOffer',
    PACKAGE_INFORMATION: 'packageInformation',
    TELE_CALLING_LEADS: 'teleCallingLeadDetails',
    PARTNER_APPROVAL: 'partnerApproval',
    SSO_WEB_VIEW: 'ssoWebView',
    WO_MULTI_TV_SUMMARY: 'woMultiTvSummary',
    DEMO_FORM: 'demoForm',
    EXCLUSIVE_STORE: 'exclusiveStore',
    TSK_VOUCHER: 'tskVoucher',
    DASHBOARD: 'dashboard',
    REDIRECT_TO_MANAGE_PACK: 'redirectToManagePack',
    PORTAL: 'qt',
    MANAGE_APPS: 'manageApps',
    AUTO_POST_WEB_VIEW: 'autoPostWebView',
    ETSK_MULTI_TV_REG: 'eTSKMulti',
    TRACK_TSRA_REQUEST: 'trackTsraRequest',
    ACTION_TSRA_REQUEST: 'actionTsraRequest',
    ACTION_TSRA_SUMMARY: 'actionTsraSummary',
    TSRA_APPROVAL_SUCCESS: 'tsraApprovalSuccess',
    PURCHASE_ORDER_TRACK_DETAILS: 'purchaseOrderTrackDetails',
    PURCHASE_ORDER_TRACK_DETAILS_ASM: 'purchaseOrderTrackDetailsASM',
    PURCHASE_ORDER_REQUEST: 'purchaseOrder',
    PURCHASE_ORDER_DURATION: 'selectDuration',
    PURCHASE_ORDER_TRACK_DETAILS_POSM: 'purchaseOrderTrackDetailsPOSM',
    PURCHASE_ORDER_TRACK_DETAILS_DEALER_POSM: 'purchaseOrderTrackDetailsDealerPOSM',
    PURCHASE_ORDER_TRACK_DETAILS_FOS_POSM: 'purchaseOrderTrackDetailsFosPOSM',
    PURCHASE_ORDER_TRACK_DETAILS_ASM_POSM: 'purchaseOrderTrackDetailsASMPOSM',
    PURCHASE_ORDER_DEALER_DURATION: 'selectDurationDealer',
    PURCHASE_ORDER_DEALER_TRACK_DETAILS: 'purchaseOrderTrackDetailsDealer',
    PURCHASE_ORDER_FOS_DURAION: 'selectDurationFos',
    PURCHASE_ORDER_ASM_DURAION: 'selectDurationASM',
    PURCHASE_ORDER_FOS_TRACK_DETAILS: 'purchaseOrderTrackDetailsfos',
    REGISTER_PAYMENT_OPTION: 'registerPaymentOptions',
    REGISTER_NEW_PAYMENT_ID: 'registerNewPayment',
    MATERIALS_SUMMARY: 'materialsSummary',
    EVD_RAISE_REQUEST_SUCCESS: 'evdRaiseRequestSuccess',
    PURCHASE_ORDER_SETTLEMENTS: 'purchaseOrderSettlements',
    TSK_CANCELLATION: 'tskCancellation',
    VALIDATE_TSK_CANCELLATION: 'validateTskCancellation',
    TSK_VOUCHER_DETAILS: 'tskVoucherDetails',
    EVD_RAISE_REQUEST: 'evdRaiseRequest',
    MATERIAL_RAISE_REQUEST: 'materialsRaiseRequest',
    ACTION_REQUEST_PO: 'actionRequestPo',
    MODIFYPACK_ACCOUNT_DETAILS: 'modifyPackAccountDetails',
    DEALER_HELP: 'dealerHelp',
    DEALER_SUCCESS: 'dealerSuccess',
    DEALER_RAISE_REQUEST: 'dealerRaiseRequest',
    DEALER_TRACK_REQUEST: 'dealerTrackRequest',
    BINGE_RETAILER: 'bingeRetailer',
    LIVE_UPDATES: 'liveUpdates',
    BINGE_RETAILER_DASHBOARD: 'bingeRetailerDashboard',
    EVD_MDN_CHANGE: 'evdMdnChange',
    DEMO_ACCOUNT_SUMMARY: 'demoAccountSummary',
    TSRA_APPROVAL: 'tsraApproval',
    REPUSH_ORDER: 'repushOrder',
    DEMO_ACCOUNT_ETSK_SUMMARY: 'demoAccountEtskSummary',
    LIVE_NEWS_TV_PAGE: 'liveNewsTvPage',
  },
};

export const VALIDATIONS = {
  REQUIRED: 'required',
  MIN_LENGTH: 'minLength',
  MAX_LENGTH: 'maxLength',
  FIX_LENGTH: 'fixLength',
  EMAIL: 'email',
  MOBILE: 'mobile',
  NUMERIC: 'numeric',
  EQUAL_WITH: 'equalWith',
  NOT_EQUAL_WITH: 'notEqualWith',
  ALLOWED_LENGTH: 'allowedLength',
  MIN_VALUE: 'minValue',
  MAX_VALUE: 'maxValue',
  RELATED_FIELD: 'relatedField',
  YES: 'Yes',
  NO: 'No',
  DEPENDENT_FIELD: 'dependentField',
  GRANTED: 'granted',
  OPTIONAL_MOBILE: 'optionalMobile',
  OPTIONAL_EMAIL: 'optionalEmail',
  ONLY_ALPHABETS: 'onlyAlphabets',
  ALPHABETS_WITH_SPACES: 'alphabetsWithSpaces',
  ADDRESS: 'address',
  STARTS_WITH: 'startWith',
  ALPHA_NUMERIC: 'alphaNumeric',
};

export const FIELD_TYPE = {
  INPUT: 'input',
  TEXTAREA: 'textArea',
  DROPDOWN: 'dropdown',
  FLAT_DROPDOWN: 'flatdropdown',
  PASSWORD: 'password',
  PHONE: 'phone',
  CHECKBOX: 'checkbox',
  SEARCH: 'search',
  DATE: 'date',
  BUTTON: 'button',
  ACCORDION: 'accordion',
  LABEL: 'label',
  TABLE: 'table',
  LIST_DATA: 'ListData',
  PIN: 'PIN',
  SELECT_LIST: 'selectList',
  AUTOCOMPLETE: 'autocomplete',
  LINK: 'link',
  RADIO: 'radio',
  MULTIPLE_SUB_ID: 'multiSubId',
  CONTAINER_BUTTON: 'containerButton',
  AMOUNT: 'amount',
  RADIO_CONTAINER: 'radioContainer',
  BALANCE_CONTAINER: 'balanceContainer',
  SELECT_SUBSCRIBER: 'selectSubscriber',
  CALL_SUBSCRIBER: 'callSubscriber',
  LINE_SEPRATOR: 'lineSeprator',
  INPUT_WITH_BUTTON: 'inputWithButton',
  CUSTOM_AMOUNT: 'customAmount',
  PILLS_GROUP: 'pillsGroup',
  DEALER_DETAILS_CARD: 'dealerDetailsCard',
  PINCODE_DETAILS_CARD: 'pincodeDetailsCard',
  SEARCH_BAR_ITEMS: 'searchBarItems',
  CUSTOMER_DETAILS_CARD: 'customerDetailsCard',
  ERROR_MESSAGE: 'errorMessage',
  MULTISELECT_DROPDOWN: 'multiSelectDropdown',
  ACTION_TILE_CARD: 'actionTileCard',
  PARTNER_APPROVAL_CARD: 'partnerApprovalCard',
  INFORMATION_TEXT: 'informationText',
  DISCLAIMER_TEXT: 'disclaimerText',
  TSRA_SUBSCRIBER_LIST: 'tsraSubscriberList',
  TOGGLE_SWITCH: 'toggleSwitch',
  ICON: 'icon',
  CONTAINER_LABEL: 'containerLabel',
  MULTI_CHECKBOX_DROPDOWN: 'multiCheckboxDropdown',
  MULTI_CHECKBOX: 'multiCheckbox',
  SELECT_DATE_RANGE: 'selectDateRange',
  SECONDARY_TABLE: 'secondaryTable',
  OFFER_SELECTION_TABLE: 'offerSelectionTable',
  INFORMATION_TEXT_OUTER: 'informationTextOuter',
  INFORMATION_CONTAINER: 'informationTextContainer',
  CUSTOMER_DETAILS: 'customerDetails',
  PARTNER_INFO: 'partnerInfo',
  SELECT_DATE: 'selectDate',
  ACTION_TILE_GROUP: 'actionTileCardGroup',
  CHECKLIST_TILES: 'checkListTiles',
  DESCRIPTION: 'description',
  FAKE_PASSWORD: 'fakePassword',
  DATE_AND_TIME: 'dateAndTime',
  TSK_INFORMATION: 'tskInformation',
  SLAB_LIST: 'slabList',
  DEALER_TEXTAREA: 'dealertextArea',
};

export const SUBMISSION = {
  SUBMIT: 'submit',
  NAVIGATION: 'navigation',
  NAVIGATION_TO: 'navigateTo',
  RESET: 'reset',
  LINK: 'link',
  UPDATE: 'update',
  SUBMIT_NAVIGATION: 'navigationWithSubmit',
  BACK: 'back',
  HOME: 'home',
  CAPTURE: 'capture',
  UPDATE_AND_SHOW: 'updateAndShow',
  CLOSE: 'close',
};

export const NAVIGATION = {
  CUSTOMER_RECHARGE: 'customerRecharge',
};

export const ALIGNMENT = {
  LEFT: 'left',
  RIGHT: 'right',
  CENTER: 'center',
};

export const ACCORDION_TYPE = {
  VALIDATE_SUBSCRIBER: 'validateSubscriberAccordian',
  RECHARGE_OFFER: 'rechargeOfferAccordian',
  SEGMENTED_OFFER: 'segmentedOffersAccordian',
  RECHARGE_WINBACK: 'rechargeWinBackAccordion',
  DYNAMIC_OFFERS: 'dynamicOffers',
  MAHA_BUMPER_OFFER: 'mahaBumperOffer',
  WINBACK_OFFER: 'winbackOffer',
  DISTRIBUTOR_DETAILS: 'distributorDetails',
  OFFERS_BASIS_RECHARGE_VALUE: 'offersBasisRechargeValue',
  ETSK: 'etsk',
  CUSTOMER_INFORMATION: 'customerInformation',
  EXISTING_BOX_DETAILS: 'existingBoxDetails',
  DEMO_ACCOUNT_DIS_DETAILS: 'demoAccountDistDetails',
  EXISTING_SUBSSCRIBER: 'existingSubscriber',
  CANCEL_TSK_DETAILS: 'cancelTSKDetails',
};

export const CONNECTION_TYPE = {
  PRIMARY: 'Primary',
  SECONDARY: 'Secondary',
};

export const BUTTON_TYPE = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
};
export const DATA_TYPE = {
  NUMBER: 'number',
};

export const KEYBOARD_TYPE = {
  NUMERIC: 'numeric',
  DEFAULT: 'default',
  NUMBER_PAD: 'number-pad',
};

export const VALUE_TYPE = {
  AMOUNT: 'amount',
  TEXT: 'text',
  CURRENCY: 'currency',
};

export const QUERY = {
  CreateSRWorkOrder: 'createSRWorkOrder',
  CreateFRWorkOrder: 'createFRWorkOrder',
  CreateFRWorkOrderOCS: 'createFRWorkOrderOCS',
  GetSlotDateForDropdown: 'getSlotDateForDropdown',
  GetSlotTimeForDropdown: 'getSlotTimeForDropdown',
  GetAvailableSlot: 'getAvailableSlot',
  GetCustomerServiceInfo: 'getCustomerServiceInfo',
  GetServiceSubCategories: 'getServiceSubCategories',
  GetSuspensionReason: 'getSuspensionReason',
  TrackServiceRequest: 'trackServiceRequest',
  AccountInformation: 'accountInformation',
  SearchAutoEvdDealers: 'searchAutoEvdDealers',
  ReplaceOffer: 'replaceOffer',
  ConfirmAddOffer: 'confirmAddOffer',
  ResendOTPWithOutSubId: 'resendOTPWithOutSubId',
  ResetEVDPin: 'resetEVDPin',
  DemoBoxDetails: 'demoBoxDetails',
  SearchDemoBoxDetails: 'searchDemoBoxDetails',
  updateEvdMdn: 'updateEvdMdn',
  dealerSearch: 'dealerSearch',
  GET_ALL_FORMS: 'getAllForms',
  GET_ALL_PATH: 'getAllPath',
  GET_ALL_ROLES: 'getAllRoles',
  WinBackSubCategoryNewRadio: 'winBackSubCategoryNewRadio',
  AddUppOffer: 'doOfferRecharge',
  GetOtpToAddOffer: 'getOtpToAddOffer',
  GetOfferPackDetails: 'getOfferPackDetails',
  ShowRechargeConfirmation: 'showRechargeConfirmation',
  GetInvoiceURL: 'getInvoiceURL',
  AddOfferPack: 'addOfferPack',
  SetSelectedOfferData: 'setSelectedOfferData',
  ResendOtpForRecharge: 'resendOtpForRecharge',
  GetTsraPartnerDetails: 'getTsraPartnerDetails',
  InvoiceTransactions: 'invoiceTransactions',
  GetFosDealerList: 'getFosDealerList',
  ApproveOTPforEVDChange: 'approveOTPforEVDChange',
  GetHotelSubscriptionURL: 'getHotelSubscriptionURL',
  GetGstInvoiceByUserId: 'getGstInvoiceByUserId',
  GetInvoiceTransactions: 'getInvoiceTransactions',
  GetURLforInvoiceTransactions: 'getURLforInvoiceTransactions',
  GstConfirmation: 'gstConfirmation',
  SearchTrackDealerFeedback: 'searchTrackDealerFeedback',
  RechargeDetails: 'rechargeDetails',
  ValidateOTPWithMobile: 'validateOTPWithMobile',
  CreateChannelPartner: 'createChannelPartner',
  ValidateOutletTypeAndFetchAllLanguages: 'validateOutletTypeAndFetchAllLanguages',
  UpdateWinBackSubscriberStatus: 'updateWinBackSubscriberStatus',
  CaptureLocationAction: 'captureLocationAction',
  GetCCPartnerDetailsBasedOnRole: 'getCCPartnerDetailsBasedOnRole',
  GetCircleUserNameEmail: 'getCircleUserNameEmail',
  ViewNewDealerASI: 'viewNewDealerASI',
  GetWorkOrderDetails: 'getWorkOrderDetails',
  GetTskAllDetails: 'getTskAllDetails',
  WorkOrderRecreation: 'workOrderRecreation',
  EtskSchedular: 'etskSchedular',
  checkRentalPackFlag: 'checkRentalPackFlag',
  doCheckRentalPackFlagPrice: 'doCheckRentalPackFlagPrice',
  GetRentalPackNew: 'getRentalPackNew',
  GetPacks: 'getPacks',
  DoPickPackAndWorkOrderCreationPrimaryAndSecondary: 'doPickPackAndWorkOrderCreationPrimaryAndSecondary',
  PrimaryTskSchedular: 'primaryTskSchedular',
  GetTskPinDetails: 'getTskPinDetails',
  GetAccountDetailsPrimaryAndSecondaryRepush: 'getAccountDetailsPrimaryAndSecondaryRepush',
  GetAllPacksProp: 'getAllPacksProp',
  GetWoRentalPack: 'getWoRentalPack',
  WoRechargeDetails: 'woRechargeDetails',
  GetUniqueKwlrtyToken: 'getUniqueKwlrtyToken',
  GetDropDownListAndRejectReasons: 'getDropDownListAndRejectReasons',
  ApprovalConfirmation: 'approvalConfirmation',
  ViewDistributorList: 'viewDistributorList',
  ViewDistributorListCSMList: 'viewDistributorListCSMList',
  GetStocksList: 'getDealerStocks',
  GetAllRePushPacksProp: 'getAllRePushPacksProp',
  eTskMultiOfrTypeDropdown: 'eTskMultiOfrTypeDropdown',
  EtskRepushSchedular: 'etskRepushSchedular',
  eTskRepushOfferDropdown: 'eTskRepushOfferDropdown',
  DoPickPackAndWorkOrderCreationSecondary: 'doPickPackAndWorkOrderCreationSecondary',
  DoRechargeETSKPickPackConfirmSlotWOrkOrderETSKPureMul: 'doRechargeETSKPickPackConfirmSlotWOrkOrderETSKPureMul',
  RejectPartnerApproval: 'rejectPartnerApproval',
  PartnerApprovalRejectAndApprove: 'partnerApprovalRejectAndApprove',
  DoBalanceEnquiryEvd: 'doBalanceEnquiryEvd',
  SetSelectedPartner: 'setSelectedPartner',
  SetInitialData: 'setInitialData',
  PartnerapprovaltracklistDetails: 'partnerapprovaltracklistDetails',
  GetSubscriberTSKDeatils: 'getSubscriberTSKDeatils',
  GET_MONTH: 'getMonth',
  GET_YEAR: 'getYear',
  loginOtpVerification: 'loginOtpVerification',
  loginWithOtp: 'loginWithOtp',
  BoxUpgradeRadioData: 'boxUpgradeRadioData',
  ModelForRMN: 'modelForRMN',
  FinalBoxUpgradation: 'finalBoxUpgradation',
  DoDemoAccountCreationAndTSKRegistration: 'doDemoAccountCreationAndTSKRegistration',
  ModelForBoxTypeChange: 'modelForBoxTypeRMN',
  TskStatusAllDetailsProcedure: 'tskStatusAllDetailsProcedure',
  GetWorkOrderDetailsBoxType: 'getWorkOrderDetailsBoxType',
  getActivationStatusOtherDetailsBoxType: 'getActivationStatusOtherDetailsBoxType',
  BoxTypeChangeRadioData: 'boxTypeChangeRadioData',
  getTskPinDetailsBoxType: 'getTskPinDetailsBoxType',
  getAccountDetailsPrimaryAndSecondaryRepushBoxType: 'getAccountDetailsPrimaryAndSecondaryRepushBoxType',
  getAllPacksPropBoxType: 'getAllPacksPropBoxType',
  getWoPacksBoxType: 'getWoPacksBoxType',
  getRentalPackBoxType: 'getRentalPackBoxType',
  boxTypeRechargeDetails: 'boxTypeRechargeDetails',
  doPickPackAndWorkOrderCreationPrimaryAndSecondaryBoxType: 'doPickPackAndWorkOrderCreationPrimaryAndSecondaryBoxType',
  boxTypeChange: 'boxTypeChange',
  proceedWithRechargeBox: 'proceedWithRechargeBox',
  FetchBingePlusPack: 'fetchBingePlusPack',
  cancelWorkorder: 'cancelWorkorder',
  isEligibleForUpgrade: 'isEligibleForUpgrade',
  ValidateEligibilityForETSK: 'validateEligibilityForETSK',
  DoGetRentalPackNewPartnerQuoteEtsk: 'doGetRentalPackNewPartnerQuoteEtsk',
  ValidateOTPForQuote: 'validateOTPForQuote',
  modalForQuotationMultiTV: 'multiTVRMNmodal',
  retrieveMultiTvTskTypeQuotation: 'retrieveMultiTvTskTypeQuotation',
  getBoxTypeQuotationMultiTV: 'getBoxType',
  getTskTypeQuotationMultiTV: 'getTskType',
  validateOTPQuotationMultiTv: 'ValidateOTPWithMobile',
  retrieveMultiTvBoxType: 'retrieveMultiTvBoxType',
  multiTvSendSms: 'multiTvSendSms',
  setMultiTvData: 'setMultiTvData',
  multiTVmobileAndEmail: 'multiTVmobileAndEmail',
  GetTskTypesFromProp: 'getTskTypesFromProp',
  RetrieveMultiTvBoxType: 'retrieveMultiTvBoxType',
  DoGetRentalPackNewPartnerQuote: 'doGetRentalPackNewPartnerQuote',
  ConnectionFilter: 'connectionFilter',
  LocationDropdown: 'locationDropdown',
  FillInTskTypeAndLocation: 'fillInTskTypeAndLocation',
  FillInOfferAndLocation: 'fillInOfferAndLocation',
  modelForBoxTypeRMN: 'modelForBoxTypeRMN',
  exitingWorkOrder: 'exitingWorkOrder',
  showExitsingBox: 'showExitsingBox',
  SendOTPToCustomer: 'sendOTPToCustomer',
  InsertRentalPackNewPartnerQuoteMod: 'insertRentalPackNewPartnerQuoteMod',
  SubmitRequestForOtp: 'submitRequestForOtp',
  sendOtpMultiTV: 'sendOTPMultiTV',
  ViewDistributorListForASM: 'viewDistributorListForASM',
  DistCodeAndName: 'distCodeAndName',
  TownDetailsFilter: 'townDetailsFilter',
  BoxTypesFilter: 'boxTypesFilter',
  GetWalkInDetailsData: 'getWalkInDetailsData',
  GetNewConnectionType: 'getNewConnectionType',
  GetSSORedirectionToken: 'getSSORedirectionToken',
  GetProductTypes: 'getProductTypes',
  GetBalanceFos: 'getBalanceFos',
  GetFtdData: 'getFtdData',
  CompetitorBoxTypeFilter: 'competitorBoxTypeFilter',
  CompetitorServiceProviderFilter: 'competitorServiceProviderFilter',
  OpenSettingsInDevice: 'openSettingsInDevice',
  GetOnlyPricePtForMultiTVInput: 'getOnlyPricePtForMultiTVInput',
  GetSecMultiTVDtlsOrg: 'getSecMultiTVDtlsOrg',
  multiTVBoxType: 'multiTVBoxType',
  submitStoreAns: 'submitStoreAns',
  getStoreOpeningStoreClosingData: 'getStoreOpeningStoreClosingData',
  submitDemoForm: 'submitDemoForm',
  GetOverThePhoneLeadDetails: 'getOverThePhoneLeadDetails',
  GetTeleCallingData: 'getTeleCallingData',
  GetOutboundActivityLeadData: 'getOutboundActivityLeadData',
  GetHomepageData: 'getHomepageData',
  GetTransactionSummary: 'getTransactionSummary',
  GetTransactionSummaryWithFilter: 'getTransactionSummaryWithFilter',
  SendSMSQuotation: 'sendSMSQuotation',
  InsertRentalPackNewPartnerQuoteSecInsMod: 'insertRentalPackNewPartnerQuoteSecInsMod',
  InsertRentalPackNewPartnerQuoteSecInsModMultiTV: 'insertRentalPackNewPartnerQuoteSecInsModMultiTV',
  GetOnlyPricePtForMultiTVInputBoxType: 'getOnlyPricePtForMultiTVInputBoxType',
  GetSecMultiTVDtlsOrgBoxType: 'getSecMultiTVDtlsOrgBoxType',
  GetBannerImages: 'getBannerImages',
  BoxTypeChangeSuccess: 'boxTypeChangeSuccess',
  SendOTPToSubscriber: 'sendOTPToSubscriber',
  ValidateOTPManageApps: 'validateOTPManageApps',
  GetTSRAApprovalList: 'getTSRAApprovalList',
  SetSelectedDealer: 'setSelectedDealer',
  DistributorTrackRequestDetails: 'distributorTrackRequestDetails',
  SearchPoTrackDetailsPOSM: 'searchPoTrackDetailsPOSM',
  SearchPoTrackDetails: 'searchPoTrackDetails',
  GetDealerTrackDetails: 'getDealerTrackDetails',
  Getfostrackrequest: 'getfostrackrequest',
  DistributorPaymentIdUpdate: 'distributorPaymentIdUpdate',
  WalletOptions: 'walletOptions',
  GetPackSelectorInfo: 'getPackSelectorInfo',
  ManageAppsModal: 'manageAppsModal',
  ManageAppsModalBack: 'manageAppsModalBack',
  FosGetRaiseRequestDetails: 'fosGetRaiseRequestDetails',
  FosApproveRequest: 'fosApproveRequest',
  GetFosRejectionReasonFromProperty: 'getFosRejectionReasonFromProperty',
  FosRejectAndReasonRequest: 'fosRejectAndReasonRequest',
  RejectReasonsPO: 'rejectReasonsPO',
  FetchSettlements: 'FetchSettlements',
  GetOrderId: 'getOrderId',
  ValidateTskCancellationModal: 'validateTskCancellationModal',
  TskCancellationModal: 'tskCancellationModal',
  CancelTskPin: 'cancelTskPin',
  ChangeBoxTypeQuotation: 'changeBoxTypeQuotation',
  DoPosmBalanceEnquiryWeb: 'doPosmBalanceEnquiryWeb',
  GetPaymentOptionsforDealerWeb: 'getPaymentOptionsforDealerWeb',
  GetPOSMData: 'getPOSMData',
  DoRaiseReqRCVTSKPOSMWeb: 'doRaiseReqRCVTSKPOSMWeb',
  DealerBalanceRequest: 'dealerBalanceRequest',
  QuotationPrimaryPincodeModal: 'quotationPrimaryPincodeModal',
  GetAllCategoryPacks: 'getAllCategoryPacks',
  CustomerInvoiceModal: 'customerInvoiceModal',
  DoRecharge: 'doRecharge',
  StoreStatus: 'storeStatus',
  DoGetPOSMAssetDetails: 'doGetPOSMAssetDetails',
  OpenEVDFormDealer: 'openEVDFormDealer',
  OpenMaterialsFormDealer: 'openMaterialsFormDealer',
  OpenEVDForm: 'openEVDForm',
  OpenMaterialsForm: 'openMaterialsForm',
  NavigateSettlements: 'navigateSettlements',
  GetPosmDealerId1: 'getPosmDealerId1',
  OpenEVDFormFos: 'openEVDFormFos',
  OpenMaterialsFormFos: 'openMaterialsFormFos',
  UpdateGST: 'updateGst',
  GetGstDetailsByUserId: 'getGstDetailsByUserId',
  OpenEVDFormASM: 'openEVDFormASM',
  OpenMaterialsFormASM: 'openMaterialsFormASM',
  GetMainCategoryBR: 'getMainCategoryBR',
  GetAllSRDetailsForLoginUser: 'getAllSRDetailsForLoginUser',
  RechargeReport: 'rechargeReport',
  ConsolidateOTFReport: 'consolidateOTFReport',
  ConsolidateBalanceTransferReport: 'consolidateBalanceTransferReport',
  ConsolidatedOnlineReport: 'consolidatedOnlineReport',
  GetRailsData:"getRailsData",
  MetaData:"metaData",
};

export const ACCOUNT_INFO = {
  customerName: 'customerName',
  subscriberID: 'subscriberID',
  subscriberMobileNumber: 'subscriberMobileNumber',
  currentBalance: 'currentBalance',
  rechargeDueDate: 'rechargeDueDate',
  recommendedMonthlyRecharge: 'recommendedMonthlyRecharge',
  basePackEndDate: 'basePackEndDate',
  connectionType: 'connectionType',
  boxType: 'boxType',
  connectionStatus: 'connectionStatus',
};

export const RADIO_GROUP = {
  RechargeFlexiPlan: 'rechargeFlexiPlan',
  OtherRechargeOption: 'otherRechargeOptions',
  MonthlyRecharge: 'recommendedMonthlyRecharge',
  RechargeBingePlan: 'rechargeBingePlan',
  RechargeWinbackFlexi: 'rechargeWinbackFlexi',
  CashbackOffers: 'cashBackOffers',
};

export const ENVIRONMENT = {
  DEVELOPMENT: 'development',
};

export const DEBOUNCE_TIMEOUT = 800;

export const SUBSCRIBER_STATUS = {
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  BLACKLISTED: 'Blacklisted',
  CANCELLED: 'Cancelled',
  CANCEL_PENDING: 'Cancel-Pending',
  DEACTIVATED: 'Deactivated',
  PENDING: 'Pending',
  SUSPENDED: 'Suspended',
  TEMP_SUSPENSION: 'Temp Suspension',
  PENDING_ACTIVATION: 'Pending Activation',
};

export const STYLE_VARIANT = {
  P1: 'P1',
  P2: 'P2',
  P3: 'P3',
  P4: 'P4',
};

export const SEARCH_LIST = {
  AUTO_EVD_DEALERS: 'autoEvdDealers',
  CUSTOMER_OFFERS: 'customerOffers',
  INVOICE_TRANSACTION: 'invoiceTransaction',
};

export const STATE_KEY = {
  FORM_STATE: 'formState',
  MODAL_STATE: 'modalState',
};

export const OTP_STRINGS = {
  ASTERISK: '*',
  CONFIRMATION: 'confirmation',
  OTP_INPUT: 'otpInput',
};

export const OFFER_TYPE = {
  dynamicOffers: 'DYNAMIC_OFFERS',
  mahaBumperOffer: 'MAHA_BUMPER_OFFERS',
  winbackOffers: 'WINBACK_OFFERS',
  myOffers: 'MY_OFFERS',
  rechargeWinback: 'RECHAARGE_WINBACK_OFFERS',
};

export const CAMPAIGN_TYPE = {
  WINBACK_LDP: 'WINBACK_LDP',
  WINBACK_D30: 'WINBACK_D30',
};

export const PACK_CATEGORY = {
  GENERIC: 'Generic',
};

export const MOENGAGE = {
  DATA_CENTER: 'DC_3',
  SW_PATH: '/serviceworker.js',
  NOTIFICATION_ENABLED: 'Push Notifications Enabled',
  NOTIFICATION_DENIED: 'Push Notifications Denied',
  PERMISSION_ERROR: 'Permission Error',
  MOENGAGE_INITIALIZED: 'MoEngage Initialized',
  INITILIZATION_ERROR: 'Initialization Error',
  PUSH_TOKEN_GENERATED: 'pushTokenGenerated',
  SDK_VERSION: '11.1.1',
  CHANNEL_ID: 'tataplay_msales',
  CHANNEL_NAME: 'msales_notification_channel',
  SOUND_NAME: 'default',
  CHANNEL_DESCRIPTION: 'Channel description',
  DEEPLINK_URL: 'tpsales://',
};

export const ACTION_TYPE = {
  USER_LOGOUT: 'user/logout',
  EVD_MDN_CHANGE_PARTNER_LIST: 'evdMdnChange/setEvdMdnPartnerFilteredList',
  STORE_OPEN: 'StoreOpen',
  STORE_CLOSE: 'StoreClose',
};

export const DYNAMIC_FORM_WIDTH_360PX = ['multiTvRegistration'];
export const DYNAMIC_FORM_WIDTH_50P = ['dealerFeedback', 'filterDealerFeedback', 'raiseDealerFeedback', 'submitDealerFeedback', 'dealerFeedbackSuccess'];
export const DYNAMIC_FORM_WIDTH_50P_WITH_PADDING = ['demoBoxDetail'];
export const DYNAMIC_FORM_WIDTH_70P = ['trackDealerFeedback'];
export const DYNAMIC_FORM_WIDTH_80P = [
  'eTSKRegistration',
  'eTSKRepushSelPacks',
  'secondaryTskRegistration',
  'registrationDetails',
  'eTSKMultiTvNoOfConnections',
  'eTSKMulti',
  'multiTvRegistration',
  'repushOrder',
  'viewNewDealer',
  'viewMyTeamDetails',
  'viewNewDealers',
  'trackPartnerRequest',
  'StoreClosing',
  'StoreOpening',
  'createChannelPartner',
  'partnerApproval',
  'manageHierarchy',
  'selectChecklist',
  'storeOperationalDetails',
  'balanceTransferDetails',
  'balanceTransferDetailsFos',
  'rechargeTransaction',
  'rechargeTransactionFos',
  'consolidatedTransaction',
  'consolidatedTransactionFos',
  'otfCreditDetails',
  'otfCreditDetailsFos',
  'competitorData',
  'demoAccountDetails',
  'demoAccountSummary',
  'demoAccountEtskSummary',
  'reports',
  'quotationETSKOffer',
  'quotationPrimaryOffer',
  'quotationMultiTVSelection',
  'exclusiveStore',
  'teleCallingLeadDetails',
  'specialComments',
  'trackTsraRequest',
  'actionTsraSummary',
  'dealerHelp',
  'demoAccount',
];
export const DYNAMIC_FORM_WIDTH_100P = ['demoBoxDetails'];

export const PERMISSION_ERROR = {
  UNKNOW_ERROR: 'Unknown Error',
  PERMISSION_DENIED_FOR_LOCATION: 'Permission Denied for Location',
  LOCATION_UNAVAILABLE: 'Location Unavailable',
  LOCATION_PERMISSION_REQUEST_TIMEOUT: 'Location Permission Request Timeout',
};

export const PARTNER_ROLES = {
  dealer: '03',
  fos: '02',
  ad: '08',
  CSM: '04',
  dis: '01',
  ASM: '06',
  ASI: '05',
};
export const ROLES = {
  dealer: 'Dealer',
  fos: 'FOS',
  ad: 'AD',
  asm: 'ASM',
  csm: 'CSM',
  asi: 'ASI',
};

export const WO_VALIDATION = {
  CANCELLED: 'Cancelled',
  OPEN: 'Open',
};

export const REDIRECTION_URL = {
  MANAGE_PACK: 'https://qa-portal.tataplay.com/inception-auth/journey/managePackRedirection-login',
  MOENGAGE_URL: 'https://dashboard-03.moengage.com/v4/auth',
};

export const REDIRECTION_LANG = {
  en: 'eng',
  hi: 'hi',
  mr: 'mar',
  ml: 'mal',
  kn: 'kan',
  bn: 'ben',
  te: 'tel',
  ta: 'tam',
  pa: 'pun',
  gu: 'guj',
  or: 'ori',
  pu: 'pun',
};

export const LOCAL_AUTH = {
  TITLE: 'Authenticate to continue',
  BIOMETRICS: 'Biometrics',
};

export const HOME_ROUTE = ['customerRecharge', 'modifyPack', 'customerInformation', 'multiTvRegistration', 'heavyRefresh', 'customerOffers'];
export const NEW_CUSTOMER_ROUTE = ['primaryTvRegistration', 'repushOrder', 'eTSKRegistration', 'eTSKRepush', 'eTSKMulti', 'activationStatus', 'quotation', 'bingeRetailer'];
export const MY_ACTION_MAIN_ROUTE = ['evdBalanceInfo', 'purchaseOrder', 'dashboard', 'dealerStock', 'viewNewDealers'];
export const MY_ACTION_ROUTE = [
  'createChannelPartner',
  'demoBoxDetail',
  'partnerApproval',
  'demoAccount',
  'tsraApproval',
  'tsraInventory',
  'storeDashboard',
  'competitorDataCapture',
  'manageApps',
];
export const OTHER_MISCELLANEOUS_ROUTE = ['liveNewsTvPage','customerActions', 'registerNewCustomer', 'faq', 'packageInformation', 'myActions', 'transaction', 'notifications'];
// Modules that do not have right icon configured in DB or overridden from old mSales
export const OTHER_CUSTOMER_ACTION_ROUTE = ['boxUpgrade', 'boxTypeChange', 'repushOrder', 'rechargeReversal', 'woRecreation'];
export const BINGE_RETAILER_ROUTE = ['manageApps', 'bingeRetailerDashboard', 'trainingModule', 'dealerHelp', 'liveUpdates'];
export const HOME_ICON: Record<string, string> = {
  customerRecharge: 'CUSTOMER_RECHARGE_HOME',
  modifyPack: 'MODIFY_PACK_PINK',
  multiTvRegistration: 'MULTI_TV_ACCOUNT_PINK',
  customerInformation: 'CUSTOMER_INFORMATION',
  heavyRefresh: 'HEAVY_REFRESH',
  customerOffers: 'CUSTOMER_OFFERS',
};
export const NEW_CUSTOMER_ICON: Record<string, string> = {
  activationStatus: 'ACTIVATION_STATUS_PINK',
  boxTypeChange: 'BOX_TYPE_CHANGE',
  eTSKRegistration: 'ETSK_REGISTRATION_PINK',
  eTSKRepush: 'ETSK_REPUSH_PINK',
  eTSKMulti: 'ETSK_MULTI',
  customerOffers: 'CUSTOMER_OFFERS',
  primaryTvRegistration: 'PRIMARY_TV_REGISTRATION',
  quotation: 'OLD_QUOTATION',
  manageApps: 'MANAGE_APP',
  bingeRetailer: 'BINGE_RETAILER',
  repushOrder: 'RE_PUSH_ORDER',
};

export const MY_ACTION_MAIN_ICON: Record<string, string> = {
  storeDashboard: 'STORE_DASHBOARD',
  dealerStock: 'DEALER_STOCK',
  evdBalanceInfo: 'EVD_BALANCE_INFO_HOME',
  viewNewDealers: 'VIEW_NEW_DEALER_PINK',
  dashboard: 'DASHBOARD',
  faq: 'FAQ_ICON',
  purchaseOrder: 'PURCHASE_ORDER',
};

export const MY_ACTION_ICON: Record<string, string> = {
  createChannelPartner: 'CREATE_CHANNEL_PARTNER',
  demoBoxDetail: 'DEMO_BOX_DETAIL',
  demoAccount: 'DEMO_ACCOUNT',
  evdBalanceInfo: 'EVD_BALANCE_INFO_HOME',
  hotelSubscription: 'HOTEL_SUBSCRIPTION',
};

export const OTHER_CUSTOMER_ACTION_ICON: Record<string, string> = {
  boxUpgrade: 'BOX_UPGRADE',
  boxTypeChange: 'BOX_TYPE_CHANGE',
  repushOrder: 'REPUSH_ORDER_HOME',
  rechargeReversal: 'RECHARGE_REVERSAL_PINK',
  woRecreation: 'WORK_ORDER',
  tskRefund: 'TSK_REFUND',
  customerService: 'RAISE_REQUEST',
  changeEVDPin: 'CHANGE_EVD_PIN',
  checkRmnUpdate: 'RMN_UPDATE',
};
export const BINGE_RETAILER_ICON: Record<string, string> = {
  trainingModule: 'TRAINING_MODULE',
  bingeRetailerDashboard: 'DASHBOARD',
  manageApps: 'MANAGE_APP',
  dealerHelp: 'DEALER_HELP',
  liveUpdates: 'LIVE_UPDATES',
};

export const ROLES_DEFAULT_ROUTES: Record<string, string> = {
  ASI: '/',
  ASM: '/',
  default: '/',
};

export const BingeRetailerData = [
  {
    menuTitle: 'New Change Pack',
    path: 'manageApps',
    menuIcon: 'MANAGE_APP',
    isModel: 0,
  },
  {
    menuTitle: 'Dashboard',
    path: 'bingeRetailerDashboard',
    menuIcon: null,
    isModel: 0,
  },
  {
    menuTitle: 'Training Module',
    path: 'trainingModule',
    menuIcon: 'TRAINING_MODULE',
    isModel: 0,
  },
  {
    menuTitle: 'Dealer Help',
    path: 'dealerHelp',
    menuIcon: 'DEALER_HELP',
    isModel: 0,
  },
  {
    menuTitle: 'Live Updates',
    path: 'liveUpdates',
    menuIcon: 'LIVE_UPDATES',
    isModel: 0,
  },
];


export const RAIL_FILTER_DEFAULT_LANGUAGES = ["English", "Tamil", "Hindi", "Telugu","malayalam","marathi"];
export const RAIL_TITLE="Live News";