export const ALERT = {
  INFO: 'info',
  SUCCESS: 'success',
  WARNING: 'warning',
  ERROR: 'error',
  CONFIRM: 'confirm',
};

export const TRANSITIONS: { FADE: 'fade'; SCALE: 'slide' } = {
  FADE: 'fade',
  SCALE: 'slide',
};

export const MODAL = {
  CLOSE: 'close',
  OK: 'ok',
  OK_GOT_IT: 'okGotIt',
  CANCEL: 'cancel',
  YES: 'yes',
  NO: 'no',
  TRY_AGAIN: 'tryAgain',
  YES_REPLACE: 'yesReplace',
  YES_APPROVE: 'yesApprove',
  YES_PROCEED: 'yesProceed',
  REJECT: 'reject',
  CONFIRM: 'confirm',
  Y: 'Yes',
  CONFRIM_RECHARGE: 'confirmRecharge',
  PROCEED: 'proceed',
  UPDATE_GST: 'updateGst',
  CONFIRM_TO_PROCEED: 'confirmToProceed',
  MODIFY: 'modify',
  OK_TO_PROCEED: 'okProceed',
  BACK: 'back',
  CHECK_WO: 'checkWO',
  OPEN_SETTINGS: 'openSettings',
  UPDATE_GST_NUMBER: 'updateGstNumber',
  PROCEED_WITHOUT_GST: 'proceedWithoutGST',
};

export const CHILD_TYPE = {
  LIST_DATA: 'listData',
  TABLE: 'table',
  TEXT: 'text',
  INFO_TEXT: 'infoText',
  INFO_TEXT_WITH_DATA: 'infoTextWithData',
  DYNAMIC_FORM: 'dynamicForm',
  LABEl: 'label',
  PACK_CARD: 'packCard',
  PARTNER_DETAILS: 'partnerDetails',
  OTP_MODAL: 'otpModal',
  DASHBOARD_MODAL: 'dashboardModal',
  RADIO_CONTAINER: 'radioContainer',
  CUSTOM_DATE_PICKER: 'customDatePicker',
  DYNAMIC_SALES_NEXT_FORM: 'dynamicSalesNextForm',
  REGISTRATION_SALES_NEXT_FORM: 'registrationSalesNextForm',
  CALENDAR: 'calendar',
  DATE_TIME: 'dateAndTime',
  SIMPLE_CALENDER: 'simpleCalender',
  PARTNER_MARGIN: 'partnerMargin',
  SEGMENTED_MARGIN: 'segmentedMargin',
  WINBACK_FLEXI_MARGIN: 'winbackFlexiMargin',
};

export const HEADER_TITLE = {
  REPLACE_OFFER: 'replaceOffer',
  TO_BE_ADDED: 'toBeAdded',
  SECURITY_CHECK: 'securityCheck',
  CONFIRMATION: 'confirmation',
  REASON_FOR_REJECTION: 'reasonForRejection',
  CUSTOMER_OFFER: 'customerOffer',
  SUBSCRIBER_ID: 'subscriberID',
  REQUEST_IN_PROCESS: 'requestInProcess',
  CONFIGURE: 'Configure',
  NO_CHANGE_FOR_AUTO_EVD_UPDATE: 'noChangeForUpdateAutoEvd',
  THIS_MODULE_IS_NOT_APPLICABLE: 'thisModuleIsNotApplicable',
  customerRechargeUPP: 'customerRechargeUPP',
  offerDetails: 'offerDetails',
  PRIMARY_TV_REGISTRATION: 'primaryTvRegistration',
  WO_RECREATION: 'woRecreation',
  MULTI_TV_REGISTRATION: 'multiTvRegistration',
  DEALER_STOCK: 'dealerStock',
  ETSK_MULTI_TV: 'etskMultiTv',
  ETSK_MULTI_TV_REPUSH: 'etskMultiTvRepush',
  ETSK_REPUSH: 'etskRepush',
  DEMO_ACC_ETSK: 'demoAcEtskRepush',
  MODIFY_PACK: 'modifyPack',
  ACTIVATION_STATUS: 'activationStatus',
  SELECT_REASON_FOR_REJECTION: 'selectReasonForRejection',
  DEMO_ACCOUNT: 'demoAccountCreation',
  STORE_DASHBOARD: 'storeDashboard',
  BOX_UPGRADE: 'boxUpgrade',
  SELECT_BOX: 'selectBox',
  RECHARGE_BOX: 'rechargeDetails',
  BOX_TYPE_CHANGE: 'boxTypeChange',
  SELECT_TSK: 'selectTsk',
  COMPETITOR_DATA_CAPTURE: 'competitorDataCapture',
  QUOTATION: 'quotation',
  QUOTATION_PRIMARY_TV: 'quotationPrimaryTV',
  QUOTATION_MULTI_TV: 'quotationMultiTV',
  QUOTATION_ETSK: 'quotationEtsk',
  SEND_QUOTE: 'sendQuote',
  WALK_IN_DETAILS: 'walkInDetails',
  TELE_CALLING_DETAILS: 'teleCallingDetails',
  OUT_BOUND_ACTIVITY: 'outBoundActivity',
  OVER_THE_PHONE: 'overThePhoneLead',
  TSK_VOUCHER: 'tskVoucher',
  CUSTOMER_INVOICE: 'customerInvoice',
  NEW_CHANGE_PACK: 'newChangePack',
  TRACK_REQUEST_EVD: 'EVD',
  METERIAL: 'meterial',
  SORT_BY: 'sortBy',
  REJECT_REASON: 'rejectReason',
  PHYSICAL_TSK_CANCELLATION: 'physicalTskCancellation',
  SPECIAL_OFFER: 'specialOffer',
};

export const CHILD_DATA = {
  ADD_OFFER_LABEl: 'addOfferLabel',
};
