import React from 'react';
import { ComponentMeta, ComponentStory } from '@storybook/react';
import { TableCell } from 'components/sales';

import Table from './Table';

export default {
  title: 'components/Table',
  component: Table,
} as ComponentMeta<typeof Table>;

export const Basic: ComponentStory<typeof Table> = (args) => <Table {...args} />;

Basic.args = {
  showPagination: false,
  totalCount: 100,
  limit: 10,
  pagination: {
    pageIndex: 0,
    pageSize: 10,
  },
  data: [
    { product: 'Test', amount: 100, discount: 5, total: 95, url: 'Nil' },
    { product: 'Test 1', amount: 200, discount: 5, total: 195, url: 'Nil' },
    { product: 'Test 2', amount: 300, discount: 5, total: 295, url: 'Nil' },
    { product: 'Test 3', amount: 400, discount: 5, total: 395, url: 'Nil' },
    { product: 'Test 4', amount: 500, discount: 5, total: 495, url: 'Nil' },
  ],
  columns: [
    {
      accessorKey: 'product',
      header: 'Product',
      cell: TableCell,
      size: 100,
      type: 'text',
      disabled: false,
      editable: true,
      enableSorting: false,
      operation: '',
      dependentId: '',
      icon: '',
      isRowFormatter: false,
      placeholder: '',
      color: '',
      fontFamily: '',
      label: 'Product',
      alignment: '',
      isBorder: false,
      isAddRemoveRequired: false,
      formName: '',
      tableHeaderStyle: {},
      maxWidthScroll: false,
    },
    {
      accessorKey: 'amount',
      header: 'Amount',
      enableSorting: true,
      cell: TableCell,
      minSize: 50,
      size: 100,
      type: 'text',
      disabled: false,
      editable: false,
      operation: '',
      dependentId: '',
      icon: '',
      isRowFormatter: false,
      placeholder: '',
      color: '',
      fontFamily: '',
      label: 'Amount',
      alignment: '',
      isBorder: false,
      isAddRemoveRequired: false,
      formName: '',
      tableHeaderStyle: {},
      maxWidthScroll: false,
    },
    {
      accessorKey: 'discount',
      header: 'Discount',
      enableSorting: true,
      cell: TableCell,
      size: 100,
      type: '',
      disabled: false,
      editable: false,
      operation: '',
      dependentId: '',
      icon: '',
      isRowFormatter: false,
      placeholder: '',
      color: '',
      fontFamily: '',
      label: 'Discount',
      alignment: '',
      isBorder: false,
      isAddRemoveRequired: false,
      formName: '',
      tableHeaderStyle: {},
      maxWidthScroll: false,
    },
    {
      accessorKey: 'total',
      header: 'Total',
      enableSorting: true,
      cell: TableCell,
      size: 100,
      type: '',
      disabled: false,
      editable: false,
      operation: '',
      dependentId: '',
      icon: '',
      isRowFormatter: false,
      placeholder: '',
      color: '',
      fontFamily: '',
      label: 'Total',
      alignment: '',
      isBorder: false,
      isAddRemoveRequired: false,
      formName: '',
      tableHeaderStyle: {},
      maxWidthScroll: false,
    },
    {
      accessorKey: 'url',
      header: 'Url',
      enableSorting: true,
      cell: TableCell,
      size: 100,
      type: 'text',
      disabled: false,
      editable: false,
      operation: '',
      dependentId: '',
      icon: '',
      isRowFormatter: false,
      placeholder: '',
      color: '',
      fontFamily: '',
      label: 'Url',
      alignment: '',
      isBorder: false,
      isAddRemoveRequired: false,
      formName: '',
      tableHeaderStyle: {},
      maxWidthScroll: false,
    },
  ],
};
