import {
  GQL_BASE_URL,
  LOAD_STORYBOOK,
  ENVIRONMENT,
  RAZORPAY_KEY,
  MOENGAGE_KEY,
  CDN_ASSETS_URL,
  PROCESS9_BASE_URL,
  MIXPANEL_PROJECT_TOKEN,
  ENABLE_MOENGAGE_MIXPANEL_EVENTS,
  ENABLE_REGISTRATION_SCHEDULER,
  DASHBOARD_EXTERNAL_URL,
  REDIRECT_AD_URL,
  AD_URL,
  AZURE_TENANT_ID,
  WEB_CLIENT_ID,
  MOBILE_CLIENT_ID,
  WEBVIEW_TRUSTED_DOMAINS

} from 'react-native-dotenv';

const env = {
  GQL_BASE_URL,
  LOAD_STORYBOOK,
  ENVIRONMENT,
  RAZORPAY_KEY,
  MOENGAGE_KEY,
  CDN_ASSETS_URL,
  PROCESS9_BASE_URL,
  MIXPANEL_PROJECT_TOKEN,
  ENABLE_MOENGAGE_MIXPANEL_EVENTS,
  ENABLE_REGISTRATION_SCHEDULER,
  DASHBOARD_EXTERNAL_URL,
  REDIRECT_AD_URL,
  AD_URL,
  AZURE_TENANT_ID,
  WEB_CLIENT_ID,
  MOBILE_CLIENT_ID,
  WEBVIEW_TRUSTED_DOMAINS

};

export default env;
